<template>
  <main class="hh-page reservation-page">
    <section class="hh-page-header d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><span class="hh-eyebrow">Admisión</span><h1 class="mb-1">Nueva reserva de cama</h1><p class="mb-0 opacity-75">Programa la cama y envía la solicitud a la estación de enfermería.</p></div><router-link to="/admision/reservas" class="btn btn-light"><i class="ph ph-list-checks me-2"></i>Ver seguimiento</router-link></section>
    <div v-if="success" class="alert alert-success d-flex align-items-start gap-2"><i class="ph ph-check-circle fs-4"></i><div><strong>Reserva enviada a la estación de enfermería</strong><div>Solicitud #{{ success.id || success.id_reserva }} creada. Enfermería debe aceptarla antes de asignar la cama.</div></div></div>
    <form v-else @submit.prevent="submit">
      <div class="row g-4">
        <div class="col-xl-5">
          <section class="card mb-4"><header class="card-header bg-transparent"><span class="step-number">1</span><div><h2 class="h5 mb-0">Paciente y admisión</h2><small class="text-muted">Identifica el paciente y su orden activa</small></div></header><div class="card-body">
            <template v-if="!contextualAdmission"><label class="form-label" for="patient-dni">Número de identificación</label><div class="input-group"><input id="patient-dni" v-model.trim="dni" class="form-control" placeholder="Digite la identificación" @keyup.enter.prevent="findPatient"><button type="button" class="btn btn-primary" :disabled="searching || !dni" @click="findPatient"><span v-if="searching" class="spinner-border spinner-border-sm"></span><i v-else class="ph ph-magnifying-glass"></i></button></div></template>
            <div v-if="patient" class="patient-chip" :class="{ 'mt-3': !contextualAdmission }"><span><i class="ph ph-user"></i></span><div><strong>{{ patientName }}</strong><small>{{ patient.identificacion || patient.dni }} · Paciente #{{ patient.paciente_id || patient.id }}</small></div><button v-if="!contextualAdmission" type="button" class="btn-close ms-auto" aria-label="Cambiar paciente" @click="clearPatient"></button><span v-else class="context-lock ms-auto"><i class="ph ph-lock-key"></i>Desde admisión</span></div>
            <div v-if="patient"><label class="form-label mt-3">Orden de trabajo</label><select v-model="form.id_orden_trabajo" class="form-select" :class="{ 'is-invalid': errors.id_orden_trabajo }" :disabled="contextualAdmission"><option value="">Selecciona una orden activa</option><option v-if="contextualAdmission && !orders.some(order => String(order.id) === String(form.id_orden_trabajo))" :value="form.id_orden_trabajo">Orden #{{ form.id_orden_trabajo }}</option><option v-for="order in orders" :key="order.id" :value="order.id">Orden #{{ order.id }} {{ order.nombre || order.descripcion ? `— ${order.nombre || order.descripcion}` : '' }}</option></select><div class="invalid-feedback">{{ fieldError('id_orden_trabajo') }}</div><small v-if="contextualAdmission" class="text-primary d-block mt-2"><i class="ph ph-lock-key me-1"></i>Orden tomada de la admisión actual.</small><small v-else-if="!loadingOrders && !orders.length" class="text-warning d-block mt-2">El paciente no tiene órdenes activas disponibles.</small></div>
          </div></section>
          <section class="card"><header class="card-header bg-transparent"><span class="step-number">2</span><div><h2 class="h5 mb-0">Programación</h2><small class="text-muted">Define cuándo y durante cuánto tiempo</small></div></header><div class="card-body"><div class="row g-3">
            <div class="col-12"><label class="form-label">Fecha y hora de inicio</label><input v-model="form.fecha_ocupacion_inicio" type="datetime-local" class="form-control" :class="{ 'is-invalid': errors.fecha_ocupacion_inicio }" @change="availabilityChanged"><div class="invalid-feedback">{{ fieldError('fecha_ocupacion_inicio') }}</div></div>
            <div class="col-sm-5"><label class="form-label">Periodo</label><div class="input-group"><input v-model.number="form.periodo" type="number" min="1" class="form-control" :class="{ 'is-invalid': errors.periodo }" @change="availabilityChanged"><span class="input-group-text">días</span></div></div>
            <div class="col-sm-7"><label class="form-label">Fecha final estimada</label><input :value="endPreview" class="form-control" disabled></div>
            <div class="col-md-6"><label class="form-label">Tipo de reserva</label><select v-model="form.tipo_reserva_id" class="form-select" @change="availabilityChanged"><option value="">Selecciona</option><option v-for="item in store.tipos" :key="item.id" :value="item.id">{{ item.nombre }}</option></select></div>
            <div class="col-md-6"><label class="form-label">Tipo de habitación</label><select v-model="roomType" class="form-select" @change="availabilityChanged"><option value="">Selecciona</option><option v-for="item in roomTypes" :key="item.id" :value="item.id">{{ item.nombre }}</option></select></div>
          </div></div></section>
        </div>
        <div class="col-xl-7"><section class="card h-100"><header class="card-header bg-transparent d-flex justify-content-between align-items-center"><div class="d-flex align-items-center"><span class="step-number">3</span><div><h2 class="h5 mb-0">Selecciona una cama</h2><small class="text-muted">La solicitud llegará a la estación indicada</small></div></div><button type="button" class="btn btn-outline-primary btn-sm" :disabled="!canSearchBeds || loadingBeds" @click="findBeds"><i class="ph ph-arrows-clockwise me-1"></i>Consultar</button></header><div class="card-body">
          <div v-if="loadingBeds" class="text-center py-5"><span class="spinner-border text-primary"></span><p class="text-muted mt-2">Consultando disponibilidad real…</p></div>
          <div v-else-if="!searchedBeds" class="reservation-empty"><i class="ph ph-calendar-check"></i><h3 class="h6">Completa la programación</h3><p>Selecciona fecha, periodo, tipo de reserva y habitación para consultar camas.</p></div>
          <div v-else-if="!beds.length" class="reservation-empty"><i class="ph ph-bed"></i><h3 class="h6">No hay camas disponibles</h3><p>Prueba con otras fechas o tipo de habitación.</p></div>
          <div v-else class="bed-options"><button v-for="bed in beds" :key="bed.id" type="button" class="bed-option" :class="{ selected: form.cama_id === bed.id }" @click="form.cama_id = bed.id"><span class="bed-icon"><i class="ph ph-bed"></i></span><span class="bed-copy"><strong>{{ bed.nombre_cama || bed.nombre }}</strong><small>{{ bed.habitacion }}</small><small><i class="ph ph-map-pin"></i>{{ locationText(bed) }}</small><em><i class="ph ph-nurse"></i>{{ bed.ubicacion?.estacion || 'Estación no informada' }}</em></span><span class="select-mark"><i class="ph ph-check"></i></span></button></div>
          <div v-if="formError" class="alert alert-danger mt-3 mb-0">{{ formError }}</div>
        </div><footer class="card-footer bg-transparent"><p v-if="!puede('hospitalizacion.reservas.crear')" class="text-danger small mb-2"><i class="ph ph-lock me-1"></i>No tiene permiso para reservar camas.</p><button v-if="puede('hospitalizacion.reservas.crear')" class="btn btn-primary w-100 py-2" :disabled="!canSubmit || saving"><span v-if="saving" class="spinner-border spinner-border-sm me-2"></span><i v-else class="ph ph-paper-plane-tilt me-2"></i>{{ saving ? 'Enviando reserva…' : 'Enviar a enfermería' }}</button></footer></section></div>
      </div>
    </form>
  </main>
</template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { obtenerMensajeError } from '@/services/api'
import { buscarPacienteExacto, consultarCamas, consultarOrdenesPaciente, listarUbicaciones } from '@/services/hospitalizacion'
import { useReservationsStore } from '@/store/pinia/reservas'
import { usePermisos } from '@/store/pinia/permisos'
// Oculta las acciones que el usuario no tiene permiso de hacer (el backend igual lo valida).
const { puede } = usePermisos()

const route = useRoute(), store = useReservationsStore(); const dni = ref(''), patient = ref(null), orders = ref([]), roomTypes = ref([]), beds = ref([]), roomType = ref(''), searching = ref(false), loadingOrders = ref(false), loadingBeds = ref(false), searchedBeds = ref(false), saving = ref(false), errors = ref({}), formError = ref(''), success = ref(null)
const contextualAdmission = computed(() => Boolean(route.query.paciente && route.query.orden))
const now = new Date(Date.now() + 60 * 60 * 1000); now.setMinutes(0, 0, 0)
const form = reactive({ paciente_id: '', id_orden_trabajo: route.query.orden || '', fecha_ocupacion_inicio: localDate(now), periodo: 1, tipo_reserva_id: '', cama_id: '' })
const patientName = computed(() => patient.value?.nombre_completo || patient.value?.nombre || [patient.value?.primer_nombre, patient.value?.primer_apellido].filter(Boolean).join(' '))
const endDate = computed(() => { if (!form.fecha_ocupacion_inicio || form.periodo < 1) return null; const value = new Date(form.fecha_ocupacion_inicio); value.setDate(value.getDate() + Number(form.periodo)); return value })
const endPreview = computed(() => endDate.value ? new Intl.DateTimeFormat('es-CO', { dateStyle: 'medium', timeStyle: 'short' }).format(endDate.value) : '—')
const canSearchBeds = computed(() => form.fecha_ocupacion_inicio && form.periodo >= 1 && form.tipo_reserva_id && roomType.value)
const canSubmit = computed(() => form.paciente_id && form.id_orden_trabajo && form.cama_id && canSearchBeds.value)
function localDate(date) { const offset = date.getTimezoneOffset(); return new Date(date.getTime() - offset * 60000).toISOString().slice(0, 16) }
function apiDate(value) { return value ? value.replace('T', ' ') + ':00' : '' }
function normalize(value) { return Array.isArray(value) ? value : value?.data || value?.ordenes || [] }
function fieldError(key) { const value = errors.value[key]; return Array.isArray(value) ? value[0] : value }
function locationText(bed) { const u = bed.ubicacion || {}; return [u.sucursal, u.torre, u.piso, u.sala].filter(Boolean).join(' · ') }
function availabilityChanged() { beds.value = []; form.cama_id = ''; searchedBeds.value = false; if (canSearchBeds.value) findBeds() }
function clearPatient() { patient.value = null; orders.value = []; form.paciente_id = ''; form.id_orden_trabajo = '' }
async function findPatient() { searching.value = true; formError.value = ''; try { const result = await buscarPacienteExacto(dni.value); patient.value = result?.data || result; form.paciente_id = patient.value.paciente_id || patient.value.id; loadingOrders.value = true; orders.value = normalize(await consultarOrdenesPaciente(form.paciente_id)); if (orders.value.length === 1) form.id_orden_trabajo = orders.value[0].id } catch (error) { formError.value = obtenerMensajeError(error); clearPatient() } finally { searching.value = false; loadingOrders.value = false } }
async function findBeds() { if (!canSearchBeds.value) return; loadingBeds.value = true; searchedBeds.value = true; form.cama_id = ''; try { beds.value = await consultarCamas({ fecha_inicio: apiDate(form.fecha_ocupacion_inicio), periodo: form.periodo, tipo_habitacion: roomType.value, tipo_reserva_id: form.tipo_reserva_id }) } catch (error) { formError.value = obtenerMensajeError(error) } finally { loadingBeds.value = false } }
async function submit() { saving.value = true; errors.value = {}; formError.value = ''; try { success.value = await store.create({ ...form, paciente_id: Number(form.paciente_id), cama_id: Number(form.cama_id), id_orden_trabajo: Number(form.id_orden_trabajo), periodo: Number(form.periodo), tipo_reserva_id: Number(form.tipo_reserva_id), fecha_ocupacion_inicio: apiDate(form.fecha_ocupacion_inicio), fecha_ocupacion_fin: endDate.value ? apiDate(localDate(endDate.value)) : undefined }) } catch (error) { if (error.status === 422) errors.value = error.payload?.errors || {}; formError.value = obtenerMensajeError(error); if (/cama|disponib/i.test(formError.value)) { form.cama_id = ''; beds.value = [] } } finally { saving.value = false } }
onMounted(async () => { try { await store.loadCatalogs(); roomTypes.value = normalize(await listarUbicaciones('tiposHabitacion')); if (route.query.paciente) { const result = await import('@/services/hospitalizacion').then(m => m.consultarPaciente(route.query.paciente)); patient.value = result?.data || result; form.paciente_id = Number(route.query.paciente); orders.value = normalize(await consultarOrdenesPaciente(form.paciente_id)) } } catch (error) { formError.value = obtenerMensajeError(error) } })
</script>
<style scoped>
.card-header{display:flex;align-items:center;gap:.8rem}.step-number{display:grid;place-items:center;width:34px;height:34px;flex:none;border-radius:10px;background:#eaf5ff;color:var(--bs-primary);font-weight:800}.patient-chip{display:flex;align-items:center;gap:.7rem;padding:.8rem;border:1px solid #cfe6f8;background:#f5fbff;border-radius:.8rem}.patient-chip>span:not(.context-lock),.bed-icon{display:grid;place-items:center;width:40px;height:40px;border-radius:11px;background:var(--bs-primary);color:#fff;font-size:1.2rem}.patient-chip strong,.patient-chip small{display:block}.patient-chip small{color:#667085}.context-lock{display:flex;align-items:center;gap:.3rem;padding:.35rem .55rem;border-radius:20px;background:#e3f2fd;color:#176da8;font-size:.68rem;font-weight:700;white-space:nowrap}.reservation-empty{text-align:center;padding:4rem 1rem;color:#667085}.reservation-empty>i{font-size:3rem;color:#aac4da}.bed-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}.bed-option{position:relative;display:flex;align-items:flex-start;gap:.75rem;text-align:left;padding:1rem;border:1px solid #e2e9f0;border-radius:1rem;background:#fff;transition:.18s}.bed-option:hover{border-color:#8fc8f0;transform:translateY(-2px);box-shadow:0 10px 25px rgba(24,99,153,.09)}.bed-option.selected{border-color:var(--bs-primary);background:#f1f8ff;box-shadow:0 0 0 2px rgba(30,134,211,.12)}.bed-copy{min-width:0}.bed-copy strong,.bed-copy small,.bed-copy em{display:block}.bed-copy small{font-size:.72rem;color:#718096;margin-top:.18rem}.bed-copy em{font-style:normal;font-size:.72rem;color:#1776b5;font-weight:600;margin-top:.45rem}.select-mark{display:none;place-items:center;position:absolute;right:.65rem;top:.65rem;width:22px;height:22px;border-radius:50%;background:var(--bs-primary);color:#fff}.selected .select-mark{display:grid}@media(max-width:767px){.bed-options{grid-template-columns:1fr}.context-lock{display:none}}
</style>
