<template>
  <div class="hh-page">
    <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4"><div><p class="text-primary fw-semibold mb-1">Pacientes</p><h2 class="mb-1">Buscar pacientes</h2><p class="text-muted mb-0">Busque por identificación, nombre, apellido u otros filtros.</p></div><router-link v-if="canCreate" to="/pacientes/nuevo" class="btn btn-primary"><i class="ri-user-add-line me-1"></i>Crear paciente</router-link></div>
    <b-card no-body class="mb-4"><b-card-header><h4 class="mb-0">Criterios de búsqueda</h4></b-card-header><b-card-body><form @submit.prevent="submitSearch"><div class="row g-3">
      <div class="col-md-4"><label for="search-dni" class="form-label">Identificación</label><input id="search-dni" v-model="store.filters.identificacion" class="form-control" placeholder="Número exacto"></div>
      <div class="col-md-4"><label for="search-name" class="form-label">Primer nombre</label><input id="search-name" v-model="store.filters.primerNombre" class="form-control" placeholder="Primer nombre"></div>
      <div class="col-md-4"><label for="search-lastname" class="form-label">Primer apellido</label><input id="search-lastname" v-model="store.filters.primerApellido" class="form-control" placeholder="Primer apellido"></div>
      <div class="col-md-6"><label for="search-country" class="form-label">País</label><select id="search-country" v-model="store.filters.paisId" class="form-select"><option value="">Todos</option><option v-for="country in store.countries" :key="country.id" :value="country.id">{{ country.nombre }}</option></select><small v-if="store.countriesError" class="text-danger">No fue posible cargar países.</small></div>
      <div class="col-md-6"><label for="search-status" class="form-label">Estados (IDs separados por coma)</label><input id="search-status" v-model="statusInput" class="form-control" placeholder="Ej. 1, 2" @change="updateStatuses"><small class="text-muted">Temporal hasta disponer del catálogo de estados.</small></div>
      <div class="col-12 d-flex flex-wrap justify-content-end gap-2"><button type="button" class="btn btn-light" @click="clear"><i class="ri-eraser-line me-1"></i>Limpiar filtros</button><button class="btn btn-primary" :disabled="store.loading"><span v-if="store.loading" class="spinner-border spinner-border-sm me-2"></span>Buscar</button></div>
    </div></form></b-card-body></b-card>

    <div class="visually-hidden" aria-live="polite">{{ liveMessage }}</div>
    <div v-if="store.error" class="alert alert-danger d-flex justify-content-between align-items-center"><span>No fue posible buscar los pacientes. {{ store.error }}</span><button class="btn btn-sm btn-outline-danger" @click="submitSearch">Reintentar</button></div>
    <b-card no-body><b-card-header v-if="store.searched && !store.loading" class="d-flex flex-wrap justify-content-between align-items-center gap-2"><h4 class="mb-0">Resultados</h4><div class="d-flex align-items-center gap-3"><span>{{ store.pagination.total }} {{ store.pagination.total === 1 ? 'paciente encontrado' : 'pacientes encontrados' }}</span><label class="d-flex align-items-center gap-2 mb-0 small">Mostrar<select v-model.number="store.pagination.perPage" class="form-select form-select-sm per-page" @change="changePerPage"><option :value="10">10</option><option :value="25">25</option><option :value="50">50</option><option :value="100">100</option></select></label></div></b-card-header><b-card-body class="p-0">
      <div v-if="!store.searched && !store.loading" class="empty-state"><i class="ri-user-search-line"></i><h4>Busque pacientes registrados.</h4><p>Presione Buscar para listar todos los pacientes o utilice los filtros para reducir los resultados.</p></div>
      <div v-else-if="store.loading" class="empty-state"><span class="spinner-border text-primary"></span><h4>Buscando pacientes…</h4></div>
      <div v-else-if="!store.results.length && !store.error" class="empty-state"><i class="ri-user-unfollow-line"></i><h4>No encontramos pacientes con los criterios ingresados.</h4><router-link v-if="canCreate" to="/pacientes/nuevo" class="btn btn-outline-primary mt-2">Crear nuevo paciente</router-link></div>
      <div v-else class="table-responsive d-none d-md-block"><table class="table align-middle mb-0"><thead><tr><th>Paciente</th><th>Documento</th><th>Nacimiento</th><th>Edad</th><th>Estado</th><th>Contacto</th><th class="text-end">Acción</th></tr></thead><tbody><tr v-for="patient in store.results" :key="patient.id"><td><strong class="d-block" v-html="highlight(patient.nombre)"></strong><small class="text-muted">{{ patient.correo || 'Correo no registrado' }}</small></td><td>{{ patient.tipoDocumento || '—' }}<strong class="d-block" v-html="highlight(patient.identificacion)"></strong></td><td>{{ formatDate(patient.fechaNacimiento) }}</td><td>{{ patient.edad ?? '—' }}</td><td><span class="badge bg-success-subtle text-success">{{ patient.estado || 'No registrado' }}</span></td><td>{{ patient.celular || 'No registrado' }}</td><td class="text-end"><button v-if="selectMode" class="btn btn-sm btn-primary" :aria-label="`Seleccionar paciente ${patient.nombre}`" @click="select(patient)">Seleccionar</button><router-link v-else :to="`/pacientes/${patient.id}`" class="btn btn-sm btn-outline-primary" :aria-label="`Ver paciente ${patient.nombre}`">Ver paciente</router-link></td></tr></tbody></table></div>
      <div v-if="store.results.length" class="d-md-none p-3"><div v-for="patient in store.results" :key="patient.id" class="patient-card"><div class="d-flex justify-content-between"><div><h5 v-html="highlight(patient.nombre)"></h5><span>{{ patient.tipoDocumento || 'Documento' }} · <span v-html="highlight(patient.identificacion)"></span></span></div><span class="badge bg-success-subtle text-success align-self-start">{{ patient.estado || 'Sin estado' }}</span></div><hr><p><i class="ri-calendar-line me-1"></i>{{ formatDate(patient.fechaNacimiento) }} · {{ patient.edad ?? '—' }} años</p><p><i class="ri-phone-line me-1"></i>{{ patient.celular || 'No registrado' }}</p><button v-if="selectMode" class="btn btn-primary w-100" @click="select(patient)">Seleccionar paciente</button><router-link v-else :to="`/pacientes/${patient.id}`" class="btn btn-outline-primary w-100">Ver paciente</router-link></div></div>
    </b-card-body><b-card-footer v-if="store.searched && !store.loading && store.pagination.total" class="d-flex flex-wrap justify-content-between align-items-center gap-2"><small class="text-muted">Página {{ store.pagination.currentPage }} de {{ store.pagination.lastPage }} · mostrando {{ pageRange }}</small><nav aria-label="Paginación de pacientes"><div class="btn-group"><button class="btn btn-sm btn-outline-secondary" :disabled="store.pagination.currentPage <= 1" @click="goToPage(1)" aria-label="Primera página"><i class="ri-skip-back-line"></i></button><button class="btn btn-sm btn-outline-secondary" :disabled="store.pagination.currentPage <= 1" @click="goToPage(store.pagination.currentPage - 1)">Anterior</button><button class="btn btn-sm btn-outline-secondary disabled" aria-current="page">{{ store.pagination.currentPage }}</button><button class="btn btn-sm btn-outline-secondary" :disabled="store.pagination.currentPage >= store.pagination.lastPage" @click="goToPage(store.pagination.currentPage + 1)">Siguiente</button><button class="btn btn-sm btn-outline-secondary" :disabled="store.pagination.currentPage >= store.pagination.lastPage" @click="goToPage(store.pagination.lastPage)" aria-label="Última página"><i class="ri-skip-forward-line"></i></button></div></nav></b-card-footer></b-card>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { usePatientsSearchStore } from '@/store/pinia/pacientes'
const store = usePatientsSearchStore(), route = useRoute(), router = useRouter(), statusInput = ref(store.filters.estados.join(', '))
const selectMode = computed(() => route.query.mode === 'select')
const permissions = (() => { try { return JSON.parse(localStorage.getItem('permissions') || '[]') } catch { return [] } })()
const permissionText = permissions.map(item => typeof item === 'string' ? item : item.name || item.nombre || '').join(' ').toLowerCase()
const canCreate = computed(() => !permissions.length || /crear.*paciente|paciente.*crear/.test(permissionText))
const liveMessage = computed(() => store.loading ? 'Buscando pacientes' : store.searched ? `${store.pagination.total} pacientes encontrados` : '')
const pageRange = computed(() => { if (!store.pagination.total) return '0 registros'; const from = (store.pagination.currentPage - 1) * store.pagination.perPage + 1; const to = Math.min(from + store.results.length - 1, store.pagination.total); return `${from}–${to} de ${store.pagination.total}` })
function updateStatuses() { store.filters.estados = [...new Set(statusInput.value.split(',').map(value => Number(value.trim())).filter(value => Number.isInteger(value) && value > 0))] }
async function submitSearch() { updateStatuses(); try { await store.searchPatients(1) } catch (error) { if (error.name !== 'AbortError') return } }
async function goToPage(page) { if (page < 1 || page > store.pagination.lastPage || page === store.pagination.currentPage) return; try { await store.searchPatients(page); window.scrollTo({ top: 0, behavior: 'smooth' }) } catch (error) { if (error.name !== 'AbortError') return } }
function changePerPage() { if (store.searched) submitSearch() }
function clear() { statusInput.value = ''; store.clearSearch() }
function select(patient) { store.selectPatient(patient); sessionStorage.setItem('selected_patient', JSON.stringify(store.selectedPatient)); router.back() }
const formatDate = value => value ? new Intl.DateTimeFormat('es-CO').format(new Date(`${value}T00:00:00`)) : 'No registrada'
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character])) }
function highlight(value) { const text = escapeHtml(value || 'No registrado'); const terms = [store.filters.identificacion, store.filters.primerNombre, store.filters.primerApellido].map(v => v.trim()).filter(Boolean); return terms.reduce((result, term) => result.replace(new RegExp(`(${term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')})`, 'ig'), '<mark>$1</mark>'), text) }
onMounted(() => store.loadCountries())
</script>

<style scoped>
.empty-state{text-align:center;padding:4rem 1rem;color:var(--bs-secondary-color)}.empty-state>i{font-size:3rem}.patient-card{padding:1rem;border:1px solid var(--bs-border-color);border-radius:.75rem;margin-bottom:1rem}.patient-card p{margin-bottom:.5rem;color:var(--bs-secondary-color)}th{white-space:nowrap;font-size:.75rem;text-transform:uppercase;color:var(--bs-secondary-color)}td{padding:1rem}.per-page{width:72px}:deep(mark){background:rgba(var(--bs-warning-rgb),.3);color:inherit;padding:0}
</style>
