<template>
  <div class="hh-page hh-detail-page"><router-link to="/pacientes" class="hh-back-link d-inline-flex align-items-center mb-3"><i class="ri-arrow-left-line me-1"></i>Volver a resultados</router-link>
    <div v-if="loading" class="text-center py-5"><span class="spinner-border text-primary"></span></div><div v-else-if="error" class="alert alert-danger">{{ error }}</div>
    <template v-else-if="patient"><div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><p class="text-primary fw-semibold mb-1">Paciente #{{ patient.paciente_id }}</p><h2 class="mb-1">{{ patient.nombre }}</h2><p class="text-muted mb-0">{{ patient.tipo_identificacion }} {{ patient.identificacion }}</p></div><button class="btn btn-primary align-self-center" @click="handleAdmission"><i :class="activeAdmission ? 'ri-file-list-3-line' : 'ri-add-circle-line'" class="me-1"></i>{{ activeAdmission ? 'Abrir admisión activa' : 'Crear admisión' }}</button></div>
      <div class="row g-4"><div class="col-lg-8"><b-card no-body class="mb-4"><b-card-header><h4 class="mb-0">Información personal</h4></b-card-header><b-card-body><div class="info-grid"><Info label="Fecha de nacimiento" :value="formatDate(patient.fecha_nacimiento)"/><Info label="Edad" :value="patient.edad == null ? '—' : `${patient.edad} años`"/><Info label="Correo" :value="patient.correo"/><Info label="Celular" :value="patient.celular"/><Info label="Teléfono" :value="patient.telefono"/><Info label="Dirección" :value="patient.direccion"/><Info label="Ubicación" :value="patient.ubicacion"/><Info label="Barrio" :value="patient.barrio"/></div></b-card-body></b-card><b-card no-body><b-card-header><h4 class="mb-0">Diagnósticos</h4></b-card-header><b-card-body><div class="mb-3"><small class="text-muted d-block">Diagnóstico principal</small><strong>{{ patient.dxprincipalcodigo }} {{ patient.dxprincipal }}</strong></div><div class="d-flex flex-wrap gap-2"><span v-for="diagnosis in patient.cie" :key="diagnosis.id" class="badge bg-primary-subtle text-primary">{{ diagnosis.codigo_cie || diagnosis.codigo }} {{ diagnosis.nombre }}</span><span v-if="!patient.cie?.length" class="text-muted">Sin diagnósticos adicionales.</span></div></b-card-body></b-card></div>
      <div class="col-lg-4"><b-card no-body class="mb-4"><b-card-header class="d-flex align-items-center justify-content-between gap-2"><h4 class="mb-0">Aseguramiento</h4><button type="button" class="btn btn-sm btn-outline-primary" @click="openContracts"><i class="ph ph-files me-1"></i>Ver contratos</button></b-card-header><b-card-body><Info label="EAPB principal" :value="patient.eapb_principal"/><hr><Info label="Tipo de usuario" :value="patient.tipo_usuario"/><hr><Info label="Rango" :value="patient.rango"/></b-card-body></b-card><b-card v-if="patient.current_location" no-body><b-card-header><h4 class="mb-0">Ubicación actual</h4></b-card-header><b-card-body><div class="location-icon"><i class="ri-map-pin-line"></i></div><h5 class="text-center">{{ patient.current_location.nombre_ubicacion || 'Ubicación clínica' }}</h5><p class="text-center text-muted">{{ patient.current_location.cama?.nombre || 'Sin cama asociada' }}</p></b-card-body></b-card></div></div>
    </template>

    <!-- La admisión se crea siempre sobre el paciente visible; por eso el modal
         no solicita identificación ni permite cambiar de paciente. -->
    <div v-if="showAdmissionModal" class="modal-backdrop-custom" @click.self="closeAdmissionModal">
      <div class="modal-card" role="dialog" aria-modal="true" aria-labelledby="admission-title">
        <div class="modal-header"><div><small class="text-primary">Nueva admisión</small><h4 id="admission-title" class="mb-0">{{ patient.nombre }}</h4></div><button type="button" class="btn-close" aria-label="Cerrar" :disabled="savingAdmission" @click="closeAdmissionModal"></button></div>
        <form @submit.prevent="createAdmission"><div class="modal-body">
          <div class="patient-context"><i class="ri-user-heart-line"></i><div><strong>{{ patient.nombre }}</strong><small>{{ patient.tipo_identificacion }} {{ patient.identificacion }} · Paciente #{{ patient.paciente_id }}</small></div></div>
          <div v-if="admissionError" class="alert alert-danger mt-3">{{ admissionError }}</div>
          <div v-if="loadingAdmissionCatalogs" class="catalog-loading mt-3"><span class="spinner-border spinner-border-sm text-primary"></span><span>Consultando vías de ingreso y contratos del paciente…</span></div>
          <div class="row g-3 mt-1">
            <div class="col-12"><label for="contract-id" class="form-label">Contrato del paciente *</label><SearchSelect id="contract-id" v-model="admissionForm.id_contrato" :options="activeContracts" :disabled="loadingAdmissionCatalogs" :value-getter="contractId" :label-getter="contractLabel" :placeholder="loadingAdmissionCatalogs?'Consultando contratos…':'Seleccione un contrato'" search-placeholder="Buscar contrato o EPS…" @change="contractAdmissionChanged"/><small v-if="!loadingAdmissionCatalogs && !activeContracts.length" class="text-danger">El paciente no tiene contratos activos para crear la admisión.</small></div>
            <div class="col-md-6"><label for="entry-route" class="form-label">Vía de ingreso *</label><SearchSelect id="entry-route" v-model="admissionForm.rips_minsalud_via_ingreso_usuario" :options="entryRoutes" :disabled="loadingAdmissionCatalogs" :value-getter="entryValue" :label-getter="optionLabel" :placeholder="loadingAdmissionCatalogs?'Consultando vías…':'Seleccione la vía de ingreso'" search-placeholder="Buscar vía de ingreso…"/></div>
            <div class="col-md-6"><label for="valid-from" class="form-label">Válida desde *</label><input id="valid-from" v-model="admissionForm.valida_desde" type="date" class="form-control" required></div>
            <div class="col-md-6"><label for="rate-id" class="form-label">Manual tarifario activo *</label><SearchSelect id="rate-id" v-model="admissionForm.id_manual" :options="manuals" :disabled="!admissionForm.id_contrato || loadingManuals" :value-getter="manualId" :label-getter="manualLabel" :placeholder="loadingManuals?'Consultando manuales…':'Seleccione un manual'" search-placeholder="Buscar manual tarifario…" @change="manualChanged"/></div>
            <div class="col-md-6"><label for="package-id" class="form-label">Paquete activo *</label><SearchSelect id="package-id" v-model="admissionForm.id_paquete" :options="packages" :disabled="!admissionForm.id_manual || loadingPackages" :value-getter="packageId" :label-getter="packageLabel" :placeholder="loadingPackages?'Consultando paquetes…':'Seleccione un paquete'" search-placeholder="Buscar paquete…" @change="packageChanged"/></div>
            <div class="col-12"><div class="services-title"><div><label class="form-label mb-0">Servicios a prestar *</label><small>Seleccione uno o varios servicios disponibles en el paquete.</small></div><button type="button" class="btn btn-sm btn-outline-primary" :disabled="!availableServiceOptions.length" @click="addService"><i class="ph ph-plus me-1"></i>Agregar servicio</button></div><div v-if="loadingServices" class="catalog-loading"><span class="spinner-border spinner-border-sm text-primary"></span>Consultando servicios disponibles…</div><div v-else-if="admissionForm.id_paquete && !services.length" class="alert alert-warning mb-0">El paquete seleccionado no tiene servicios activos.</div><div v-else class="selected-services"><div v-for="(row,index) in selectedServices" :key="row.key" class="service-row"><div><label :for="`service-${row.key}`" class="form-label">Servicio {{ index+1 }}</label><SearchSelect :id="`service-${row.key}`" v-model="row.id_servicio" :options="serviceOptionsFor(row)" :value-getter="serviceId" :label-getter="serviceLabel" placeholder="Seleccione un servicio" search-placeholder="Buscar servicio…"/></div><div><label :for="`quantity-${row.key}`" class="form-label">Cantidad</label><input :id="`quantity-${row.key}`" v-model.number="row.cantidad" type="number" min="1" class="form-control" required></div><button type="button" class="btn btn-sm btn-outline-danger" :disabled="selectedServices.length===1" title="Quitar servicio" @click="removeService(index)"><i class="ph ph-trash"></i></button></div></div></div>
          </div>
        </div><div class="modal-footer"><button type="button" class="btn btn-light" :disabled="savingAdmission" @click="closeAdmissionModal">Cancelar</button><button class="btn btn-primary" :disabled="!canCreateAdmission"><span v-if="savingAdmission" class="spinner-border spinner-border-sm me-2"></span>{{ savingAdmission ? 'Creando admisión…' : 'Crear admisión' }}</button></div></form>
      </div>
    </div>

    <div v-if="showContractsModal" class="modal-backdrop-custom" @click.self="closeContracts">
      <div class="modal-card contracts-modal" role="dialog" aria-modal="true" aria-labelledby="contracts-title">
        <div class="modal-header"><div><small class="text-primary">ASEGURAMIENTO DEL PACIENTE</small><h4 id="contracts-title" class="mb-0">Contratos asociados</h4></div><button type="button" class="btn-close" :disabled="savingContract" @click="closeContracts"></button></div>
        <div class="modal-body">
          <div class="patient-context"><i class="ph ph-identification-card"></i><div><strong>{{ patient.nombre }}</strong><small>{{ patient.tipo_identificacion }} {{ patient.identificacion }}</small></div></div>
          <div v-if="contractsError" class="alert alert-danger mt-3">{{ contractsError }}</div><div v-if="contractsNotice" class="alert alert-success mt-3">{{ contractsNotice }}</div>
          <form class="add-contract" @submit.prevent="addContract"><div><label for="new-contract" class="form-label">Agregar contrato</label><SearchSelect id="new-contract" v-model="newContractId" :options="availableContracts" :disabled="loadingContracts || savingContract" :value-getter="contractId" :label-getter="contractLabel" placeholder="Seleccione un contrato disponible" search-placeholder="Buscar contrato o EPS…"/></div><button class="btn btn-primary" :disabled="savingContract || loadingContracts || !newContractId"><span v-if="savingContract" class="spinner-border spinner-border-sm me-1"></span>{{ savingContract ? 'Agregando…' : 'Agregar' }}</button></form>
          <div class="contracts-heading"><div><small>CONTRATOS DEL PACIENTE</small><strong>{{ contracts.length }} registros</strong></div><button type="button" class="btn btn-sm btn-outline-primary" :disabled="loadingContracts" @click="loadContracts"><i class="ph ph-arrows-clockwise"></i></button></div>
          <div v-if="loadingContracts" class="text-center py-4"><span class="spinner-border text-primary"></span><p class="text-muted mt-2 mb-0">Consultando contratos…</p></div>
          <div v-else-if="!contracts.length" class="contracts-empty"><i class="ph ph-file-x"></i><p>El paciente todavía no tiene contratos asociados.</p></div>
          <div v-else class="contracts-list"><article v-for="item in contracts" :key="relationId(item)"><span :class="{active:isContractActive(item)}"><i class="ph ph-file-text"></i></span><div><small>CONTRATO #{{ contractId(item) }}</small><strong>{{ contractLabel(item) }}</strong><em :class="{active:isContractActive(item)}">{{ isContractActive(item) ? 'Activo' : 'Inactivo' }}</em></div><button type="button" class="btn btn-sm" :class="isContractActive(item)?'btn-outline-danger':'btn-outline-success'" :disabled="savingContractId===relationId(item)" @click="toggleContract(item)"><span v-if="savingContractId===relationId(item)" class="spinner-border spinner-border-sm me-1"></span>{{ savingContractId===relationId(item) ? 'Guardando…' : isContractActive(item) ? 'Inactivar' : 'Activar' }}</button></article></div>
        </div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" :disabled="savingContract || savingContractId" @click="closeContracts">Cerrar</button></div>
      </div>
    </div>
  </div>
</template>
<script setup>
import { computed, defineComponent, h, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { obtenerMensajeError } from '@/services/api'
import { agregarContratoPaciente, cambiarEstadoContratoPaciente, consultarContratosDisponibles, consultarContratosPaciente, consultarManualesContrato, consultarPaciente, consultarPaquetesActivosManual, consultarServiciosPaquete, consultarTiposIngresoAtencion, crearOrden } from '@/services/hospitalizacion'
import SearchSelect from '@/components/form/SearchSelect.vue'
const Info = defineComponent({ props: { label: String, value: [String, Number] }, setup: p => () => h('div', [h('small', { class: 'text-muted d-block' }, p.label), h('strong', p.value || 'No registrado')]) })
const route = useRoute(), router = useRouter(), patient = ref(null), loading = ref(true), error = ref('')
const showAdmissionModal = ref(false), savingAdmission = ref(false), loadingAdmissionCatalogs = ref(false), admissionError = ref(''), entryRoutes = ref([]), contracts = ref([])
const manuals=ref([]),packages=ref([]),services=ref([]),loadingManuals=ref(false),loadingPackages=ref(false),loadingServices=ref(false),selectedServices=ref([])
const showContractsModal=ref(false),loadingContracts=ref(false),savingContract=ref(false),savingContractId=ref(''),contractsError=ref(''),contractsNotice=ref(''),allContracts=ref([]),newContractId=ref('')
const admissionForm = reactive({ id_contrato:'', id_manual:'', id_paquete:'', id_paquete_manual_tarifario:'', valida_desde: new Date().toISOString().slice(0, 10), rips_minsalud_via_ingreso_usuario:'' })
const activeAdmission = computed(() => patient.value?.orden_de_trabajo || null)
const formatDate = value => value ? new Intl.DateTimeFormat('es-CO').format(new Date(`${value}T00:00:00`)) : 'No registrada'
const array = value => { if(Array.isArray(value))return value;for(const key of ['data','contratos','manuales','paquetes','servicios','items','tipos_ingreso','tiposIngreso']){if(Array.isArray(value?.[key]))return value[key];if(value?.[key]&&typeof value[key]==='object'){const nested=array(value[key]);if(nested.length)return nested}}return[] }
const optionId = item => item?.id_manual ?? item?.id_manual_tarifario ?? item?.id_paquete_manual_tarifario ?? item?.id_paquete ?? item?.id_servicio ?? item?.servicio?.id ?? item?.id_contrato ?? item?.id ?? item?.value
// Nunca se permite que el ID del contrato sea usado como ID del manual.
const manualId=item=>item?.id_manual??item?.id_manual_tarifario??item?.id_paquete_manual_tarifario??item?.manual?.id??item?.manual_tarifario?.id??item?.manualTarifario?.id??item?.id
const packageId=item=>item?.id_paquete??item?.paquete?.id??item?.package_id??item?.id
const serviceId=item=>item?.id_servicio??item?.servicio?.id??item?.service_id??item?.id
const contractId = item => item?.id_contrato ?? item?.contrato?.id ?? item?.contrato_id ?? item?.id
const relationId = item => item?.id_paciente_contrato ?? item?.id_relacion ?? item?.pivot?.id ?? item?.id
const isContractActive = item => ![false,0,'0','false','inactivo'].includes(item?.status ?? item?.activo ?? item?.pivot?.status ?? true)
const activeContracts = computed(()=>contracts.value.filter(isContractActive))
const availableContracts = computed(()=>{const associated=new Set(contracts.value.map(item=>String(contractId(item))));return allContracts.value.filter(item=>!associated.has(String(contractId(item))))})
const selectedServiceIds=computed(()=>new Set(selectedServices.value.map(row=>String(row.id_servicio)).filter(Boolean)))
const availableServiceOptions=computed(()=>services.value.filter(item=>!selectedServiceIds.value.has(String(serviceId(item)))))
const canCreateAdmission=computed(()=>{const ids=selectedServices.value.map(row=>String(row.id_servicio)).filter(Boolean);return !savingAdmission.value&&!loadingAdmissionCatalogs.value&&!loadingManuals.value&&!loadingPackages.value&&!loadingServices.value&&activeContracts.value.length&&admissionForm.id_contrato&&admissionForm.id_manual&&admissionForm.id_paquete_manual_tarifario&&admissionForm.id_paquete&&selectedServices.value.length>=1&&selectedServices.value.length<=100&&ids.length===selectedServices.value.length&&new Set(ids).size===ids.length&&selectedServices.value.every(row=>Number(row.cantidad)>0)})
const entryValue = item => item?.codigo ?? item?.valor ?? item?.value ?? item?.id
const optionLabel = item => [item?.codigo, item?.nombre ?? item?.descripcion ?? item?.name ?? item?.tag].filter(Boolean).join(' — ') || `Registro ${optionId(item)}`
const manualLabel=item=>[item?.codigo??item?.manual?.codigo??item?.manual_tarifario?.codigo,item?.nombre??item?.manual?.nombre??item?.manual_tarifario?.nombre??item?.descripcion].filter(Boolean).join(' — ')||`Manual #${manualId(item)}`
const packageLabel=item=>[item?.codigo??item?.paquete?.codigo,item?.nombre??item?.paquete?.nombre??item?.descripcion].filter(Boolean).join(' — ')||`Paquete #${packageId(item)}`
const serviceLabel=item=>[item?.codigo??item?.servicio?.codigo,item?.nombre??item?.servicio?.nombre??item?.descripcion].filter(Boolean).join(' — ')||`Servicio #${serviceId(item)}`
const contractLabel = item => [item?.nombre ?? item?.contrato?.nombre ?? (typeof item?.contrato==='string'?item.contrato:null) ?? item?.name, item?.tercero?.nombre ?? item?.tercero ?? item?.eps ?? item?.tercero_contratante?.nombre].filter(Boolean).join(' — ') || `Contrato #${contractId(item)}`
const newServiceRow=()=>({key:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,id_servicio:'',cantidad:1})
function resetAdmissionDependencies(level='contract'){if(level==='contract'){manuals.value=[];admissionForm.id_manual=''}if(['contract','manual'].includes(level)){packages.value=[];admissionForm.id_paquete='';admissionForm.id_paquete_manual_tarifario=''}services.value=[];selectedServices.value=[newServiceRow()]}
async function contractAdmissionChanged(){resetAdmissionDependencies('contract');if(!admissionForm.id_contrato)return;loadingManuals.value=true;admissionError.value='';try{manuals.value=array(await consultarManualesContrato(admissionForm.id_contrato)).filter(item=>manualId(item)!=null);if(manuals.value.length===1){admissionForm.id_manual=manualId(manuals.value[0]);await manualChanged()}}catch(reason){admissionError.value=obtenerMensajeError(reason)}finally{loadingManuals.value=false}}
async function manualChanged(){resetAdmissionDependencies('manual');const selectedManualId=admissionForm.id_manual;if(!selectedManualId)return;loadingPackages.value=true;admissionError.value='';try{packages.value=array(await consultarPaquetesActivosManual(selectedManualId)).filter(item=>packageId(item)!=null);if(packages.value.length===1){admissionForm.id_paquete=packageId(packages.value[0]);await packageChanged()}}catch(reason){admissionError.value=obtenerMensajeError(reason)}finally{loadingPackages.value=false}}
async function packageChanged(){services.value=[];selectedServices.value=[newServiceRow()];admissionForm.id_paquete_manual_tarifario='';if(!admissionForm.id_paquete)return;const selectedPackage=packages.value.find(item=>String(packageId(item))===String(admissionForm.id_paquete));admissionForm.id_paquete_manual_tarifario=selectedPackage?.id_paquete_manual_tarifario??selectedPackage?.id??'';loadingServices.value=true;admissionError.value='';try{services.value=array(await consultarServiciosPaquete(admissionForm.id_paquete)).filter(item=>serviceId(item)!=null);if(services.value.length===1)selectedServices.value[0].id_servicio=serviceId(services.value[0])}catch(reason){admissionError.value=obtenerMensajeError(reason)}finally{loadingServices.value=false}}
function serviceOptionsFor(row){return services.value.filter(item=>String(serviceId(item))===String(row.id_servicio)||!selectedServiceIds.value.has(String(serviceId(item))))}
function addService(){if(selectedServices.value.length<100&&availableServiceOptions.value.length)selectedServices.value.push(newServiceRow())}
function removeService(index){if(selectedServices.value.length>1)selectedServices.value.splice(index,1)}
async function loadAdmissionCatalogs(){loadingAdmissionCatalogs.value=true;admissionError.value='';entryRoutes.value=[];contracts.value=[];try{const[routesResponse,contractsResponse]=await Promise.all([consultarTiposIngresoAtencion(),consultarContratosPaciente(patient.value.paciente_id)]);entryRoutes.value=array(routesResponse);contracts.value=array(contractsResponse);if(entryRoutes.value.length===1)admissionForm.rips_minsalud_via_ingreso_usuario=entryValue(entryRoutes.value[0]);if(activeContracts.value.length===1){admissionForm.id_contrato=contractId(activeContracts.value[0]);await contractAdmissionChanged()}}catch(reason){admissionError.value=obtenerMensajeError(reason)}finally{loadingAdmissionCatalogs.value=false}}
function handleAdmission() { const orderId = activeAdmission.value?.id; if (orderId) { router.push(`/admisiones/${orderId}`); return } Object.assign(admissionForm,{id_contrato:'',id_manual:'',id_paquete:'',id_paquete_manual_tarifario:'',rips_minsalud_via_ingreso_usuario:''});resetAdmissionDependencies('contract');showAdmissionModal.value=true;loadAdmissionCatalogs() }
function closeAdmissionModal() { if (!savingAdmission.value) { showAdmissionModal.value = false; admissionError.value = '' } }
async function loadContracts(){loadingContracts.value=true;contractsError.value='';try{const[patientContracts,catalog]=await Promise.all([consultarContratosPaciente(patient.value.paciente_id),consultarContratosDisponibles()]);contracts.value=array(patientContracts);allContracts.value=array(catalog)}catch(reason){contractsError.value=obtenerMensajeError(reason)}finally{loadingContracts.value=false}}
function openContracts(){showContractsModal.value=true;newContractId.value='';contractsNotice.value='';loadContracts()}
function closeContracts(){if(!savingContract.value&&!savingContractId.value)showContractsModal.value=false}
async function addContract(){if(savingContract.value||!newContractId.value)return;savingContract.value=true;contractsError.value='';contractsNotice.value='';try{await agregarContratoPaciente(patient.value.paciente_id,newContractId.value);contractsNotice.value='Contrato agregado correctamente.';newContractId.value='';await loadContracts()}catch(reason){contractsError.value=obtenerMensajeError(reason)}finally{savingContract.value=false}}
async function toggleContract(item){const id=relationId(item);if(!id||savingContractId.value)return;savingContractId.value=id;contractsError.value='';contractsNotice.value='';const nextStatus=!isContractActive(item);try{await cambiarEstadoContratoPaciente(patient.value.paciente_id,id,nextStatus);contractsNotice.value=`Contrato ${nextStatus?'activado':'inactivado'} correctamente.`;await loadContracts()}catch(reason){contractsError.value=obtenerMensajeError(reason)}finally{savingContractId.value=''}}
async function createAdmission() {
  if (savingAdmission.value) return
  savingAdmission.value = true; admissionError.value = ''
  try {
    const response = await crearOrden({ id_paquete: Number(admissionForm.id_paquete), id_paquete_manual_tarifario: Number(admissionForm.id_paquete_manual_tarifario), id_paciente: Number(patient.value.paciente_id), valida_desde: admissionForm.valida_desde, rips_minsalud_via_ingreso_usuario: admissionForm.rips_minsalud_via_ingreso_usuario || null, servicios: selectedServices.value.map(row=>({id_servicio:Number(row.id_servicio),cantidad:Number(row.cantidad)})) })
    // El ID permite abrir inmediatamente la admisión. Si el backend aún no lo
    // devuelve, recargamos el paciente para obtener su nueva orden activa.
    let orderId = response.id_orden_trabajo
    if (!orderId) { patient.value = await consultarPaciente(patient.value.paciente_id); orderId = patient.value.orden_de_trabajo?.id }
    if (orderId) { showAdmissionModal.value = false; await router.push(`/admisiones/${orderId}`) }
    else admissionError.value = 'La admisión fue creada, pero la API no devolvió su identificador.'
  } catch (reason) { admissionError.value = obtenerMensajeError(reason) } finally { savingAdmission.value = false }
}
onMounted(async () => { try { patient.value = await consultarPaciente(route.params.id) } catch (reason) { error.value = obtenerMensajeError(reason) } finally { loading.value = false } })
</script>
<style scoped>
.add-contract{display:grid;grid-template-columns:1fr auto;align-items:end;gap:.65rem;margin-top:1rem;padding:.85rem;border:1px solid #dce7ed;border-radius:.75rem;background:#f7fafc}.contracts-heading{display:flex;align-items:center;justify-content:space-between;margin-top:1rem;padding-bottom:.6rem;border-bottom:1px solid #e2e8ed}.contracts-heading small,.contracts-heading strong{display:block}.contracts-heading small{color:#7c8996;font-size:.65rem}.contracts-list{display:grid;gap:.55rem;margin-top:.7rem}.contracts-list article{display:flex;align-items:center;gap:.7rem;padding:.75rem;border:1px solid #e0e7ec;border-radius:.7rem;background:#fff}.contracts-list article>span{display:grid;place-items:center;width:38px;height:38px;flex:none;border-radius:10px;background:#f1f3f5;color:#758492}.contracts-list article>span.active{background:#e6f7ee;color:#25815c}.contracts-list article>div{min-width:0;flex:1}.contracts-list small,.contracts-list strong,.contracts-list em{display:block}.contracts-list small{color:#7b8996;font-size:.63rem}.contracts-list strong{font-size:.76rem}.contracts-list em{width:max-content;margin-top:.2rem;padding:.16rem .42rem;border-radius:20px;background:#f0f2f4;color:#687784;font-size:.62rem;font-style:normal}.contracts-list em.active{background:#e6f7ee;color:#25815c}.contracts-empty{display:grid;place-items:center;padding:2rem;color:#788794;text-align:center}.contracts-empty i{font-size:2rem}.contracts-empty p{margin:.4rem 0}.contracts-modal{width:min(760px,100%)}@media(max-width:575px){.add-contract{grid-template-columns:1fr}.contracts-list article{align-items:flex-start;flex-wrap:wrap}.contracts-list article>button{width:100%}}
.services-title{display:flex;align-items:end;justify-content:space-between;gap:.7rem;margin-top:.25rem}.services-title small{display:block;color:#7a8996}.selected-services{display:grid;gap:.55rem;margin-top:.65rem}.service-row{display:grid;grid-template-columns:minmax(0,1fr) 110px auto;align-items:end;gap:.55rem;padding:.7rem;border:1px solid #e0e7ec;border-radius:.7rem;background:#f8fafb}.service-row>button{margin-bottom:.1rem}@media(max-width:575px){.services-title{align-items:flex-start;flex-direction:column}.service-row{grid-template-columns:1fr 90px}.service-row>button{grid-column:1/-1;width:100%}}
</style>
<style scoped>.info-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1.5rem}.location-icon{width:60px;height:60px;border-radius:50%;display:grid;place-items:center;margin:0 auto 1rem;background:rgba(var(--bs-primary-rgb),.12);color:var(--bs-primary);font-size:1.6rem}.modal-backdrop-custom{position:fixed;inset:0;z-index:1080;display:grid;place-items:center;padding:1rem;background:rgba(15,23,42,.58)}.modal-card{width:min(680px,100%);max-height:calc(100vh - 2rem);overflow:auto;background:var(--bs-body-bg);border-radius:1rem;box-shadow:0 24px 60px rgba(0,0,0,.25)}.modal-header,.modal-footer{padding:1rem 1.25rem}.modal-body{padding:1.25rem}.patient-context{display:flex;align-items:center;gap:1rem;padding:1rem;border-radius:.75rem;background:var(--bs-tertiary-bg)}.patient-context>i{font-size:1.7rem;color:var(--bs-primary)}.patient-context div{display:flex;flex-direction:column}.patient-context small{color:var(--bs-secondary-color)}@media(max-width:575px){.info-grid{grid-template-columns:1fr}}</style>
