import{apiRequest,toQuery}from'./api'
const post=(path,body={})=>apiRequest(path,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`},body:JSON.stringify(body)})
export const listarRecursoFacturacion=(resource,filters={})=>apiRequest(`/v1/facturacion/${resource}${toQuery(filters)}`)
export const crearCuentaOrden=orden=>post(`/v1/facturacion/ordenes/${encodeURIComponent(orden)}/cuenta`)
export const consultarCuenta=id=>apiRequest(`/v1/facturacion/cuentas/${encodeURIComponent(id)}`)
export const consultarCargosCuenta=id=>apiRequest(`/v1/facturacion/cuentas/${encodeURIComponent(id)}/cargos`)
export const sincronizarCargos=id=>post(`/v1/facturacion/cuentas/${encodeURIComponent(id)}/sincronizar-cargos`)
export const crearCargoManual=(id,payload)=>post(`/v1/facturacion/cuentas/${encodeURIComponent(id)}/cargos-manuales`,payload)
export const anularCargo=(id,motivo)=>post(`/v1/facturacion/cargos/${encodeURIComponent(id)}/anular`,{motivo})
export const liquidarCuenta=id=>post(`/v1/facturacion/cuentas/${encodeURIComponent(id)}/liquidar`)
export const cerrarCuenta=(id,motivo='')=>post(`/v1/facturacion/cuentas/${encodeURIComponent(id)}/cerrar`,{motivo})
export const reabrirCuenta=(id,motivo)=>post(`/v1/facturacion/cuentas/${encodeURIComponent(id)}/reabrir`,{motivo})
export const facturarCuenta=id=>post(`/v1/facturacion/cuentas/${encodeURIComponent(id)}/facturas`)
export const consultarFactura=id=>apiRequest(`/v1/facturacion/facturas/${encodeURIComponent(id)}`)
export const transmitirFactura=id=>post(`/v1/facturacion/facturas/${encodeURIComponent(id)}/transmitir`)
export const radicarFactura=(id,payload)=>post(`/v1/facturacion/facturas/${encodeURIComponent(id)}/radicar`,payload)
export const crearGlosa=(id,payload)=>post(`/v1/facturacion/facturas/${encodeURIComponent(id)}/glosas`,payload)
export const responderGlosa=(id,payload)=>post(`/v1/facturacion/glosas/${encodeURIComponent(id)}/respuestas`,payload)
export const registrarPago=(id,payload)=>post(`/v1/facturacion/facturas/${encodeURIComponent(id)}/pagos`,payload)
