<template>
  <main class="hh-page referrals-page">
    <section class="referral-hero"><div><span>GESTIÓN ASISTENCIAL</span><h1>Referencia y contrarreferencia</h1><p>Bandeja operativa para coordinar el traslado y la continuidad clínica de los pacientes.</p></div><div class="hero-actions"><router-link to="/referencias/establecimientos" class="btn btn-outline-light"><i class="ph ph-buildings me-1"></i>Establecimientos</router-link><router-link to="/contrareferencias" class="btn btn-outline-light"><i class="ph ph-arrow-bend-up-left me-1"></i>Contrarreferencias</router-link><router-link to="/referencias/autorizaciones" class="btn btn-outline-light"><i class="ph ph-seal-check me-1"></i>Autorizaciones</router-link><router-link to="/referencias/nueva" class="btn btn-light text-primary"><i class="ph ph-plus me-1"></i>Nueva referencia</router-link></div></section>

    <div class="metric-grid mt-4"><article><span class="blue"><i class="ph ph-files"></i></span><div><small>Total referencias</small><strong>{{ stats.total_referencias ?? references.length }}</strong></div></article><article><span class="amber"><i class="ph ph-clock-countdown"></i></span><div><small>Pendientes</small><strong>{{ stats.pendientes ?? pendingCount }}</strong></div></article><article><span class="green"><i class="ph ph-check-circle"></i></span><div><small>Completadas</small><strong>{{ stats.completadas ?? completedCount }}</strong></div></article><article><span class="purple"><i class="ph ph-timer"></i></span><div><small>Tiempo promedio</small><strong>{{ stats.tiempo_promedio_atencion ?? '—' }}<em v-if="stats.tiempo_promedio_atencion"> h</em></strong></div></article></div>

    <b-card no-body class="filters-card mt-4"><b-card-body><form class="row g-3" @submit.prevent="load"><div class="col-md-4 col-xl-3"><label class="form-label">Estado</label><select v-model="filters.estado_id" class="form-select"><option value="">Todos</option><option v-for="item in catalogs.estados" :key="item.id" :value="item.id">{{ item.nombre }}</option></select></div><div class="col-md-4 col-xl-3"><label class="form-label">Prioridad</label><select v-model="filters.prioridad_id" class="form-select"><option value="">Todas</option><option v-for="item in catalogs.prioridades" :key="item.id" :value="item.id">{{ item.nombre }}</option></select></div><div class="col-md-4 col-xl-3"><label class="form-label">Desde</label><input v-model="filters.fecha_inicio" type="date" class="form-control"></div><div class="col-md-4 col-xl-3"><label class="form-label">Hasta</label><input v-model="filters.fecha_fin" type="date" class="form-control"></div><div class="col-md-8 col-xl-6"><label class="form-label">Médico que refiere</label><input v-model.trim="filters.medico_refiere" class="form-control" placeholder="Nombre del médico externo"></div><div class="col-md-4 col-xl-3"><label class="form-label">Vista operativa</label><select v-model="view" class="form-select"><option value="all">Todas</option><option value="pending">Solo pendientes</option></select></div><div class="col-md-12 col-xl-3 d-flex align-items-end justify-content-end gap-2"><button type="button" class="btn btn-outline-secondary" @click="clear">Limpiar</button><button class="btn btn-primary px-4" :disabled="loading"><span v-if="loading" class="spinner-border spinner-border-sm me-2"></span>Buscar</button></div></form></b-card-body></b-card>

    <div v-if="error" class="alert alert-danger mt-3">{{ error }}</div>
    <b-card no-body class="results-card mt-4"><b-card-header><div><small>BANDEJA OPERATIVA</small><h4 class="mb-0">{{ view === 'pending' ? 'Referencias pendientes' : 'Referencias registradas' }}</h4></div><div class="local-search"><i class="ph ph-magnifying-glass"></i><input v-model="localSearch" placeholder="Buscar en resultados"><span>{{ filtered.length }}</span></div></b-card-header><div v-if="!loading && !filtered.length" class="empty"><i class="ph ph-files"></i><h3>No hay referencias</h3><p>No se encontraron registros con los filtros seleccionados.</p></div><div v-else class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Referencia</th><th>Paciente</th><th>Origen</th><th>Prioridad</th><th>Tipo</th><th>Estado</th><th>Médico receptor</th><th></th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id"><td><strong class="reference-number">{{ item.numero_referencia || `#${item.id}` }}</strong><small class="cell-sub">{{ formatDate(item.fecha_referencia || item.created_at) }}</small></td><td><strong class="cell-main">{{ item.paciente?.nombre || item.paciente?.nombre_completo || 'Paciente no informado' }}</strong><small class="cell-sub">{{ item.paciente?.identificacion }}</small></td><td><span class="cell-text">{{ item.establecimiento_origen?.nombre || 'No informado' }}</span></td><td><span class="priority" :style="{ '--status': item.prioridad?.color || '#d8872e' }">{{ item.prioridad?.nombre || 'Sin prioridad' }}</span></td><td><span class="cell-text">{{ item.tipo_referencia?.nombre || '—' }}</span></td><td><span class="status" :style="{ '--status': item.estado?.color || '#5b7083' }"><i class="ph ph-circle-fill"></i>{{ item.estado?.nombre || item.estado?.codigo || 'Sin estado' }}</span></td><td><span class="cell-text">{{ item.medico_receptor?.name || item.medico_receptor?.nombre || 'Por asignar' }}</span></td><td class="text-end"><router-link :to="`/referencias/${item.id}`" class="btn btn-sm btn-outline-primary">Gestionar <i class="ph ph-arrow-right ms-1"></i></router-link></td></tr></tbody></table></div></b-card>
  </main>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { obtenerMensajeError } from '@/services/api'
import { consultarCatalogosReferencia, consultarEstadisticasReferencias, listarReferencias, listarReferenciasPendientes } from '@/services/referencias'
const references=ref([]),stats=ref({}),loading=ref(false),error=ref(''),view=ref('all'),localSearch=ref(''),catalogs=reactive({estados:[],prioridades:[]}),filters=reactive({estado_id:'',prioridad_id:'',fecha_inicio:'',fecha_fin:'',medico_refiere:''});let controller=null
const array=value=>Array.isArray(value)?value:Array.isArray(value?.data)?value.data:[]
const pick=(source,names)=>{for(const name of names)if(Array.isArray(source?.[name]))return source[name];return[]}
const filtered=computed(()=>{const term=localSearch.value.toLowerCase();return references.value.filter(item=>[item.numero_referencia,item.paciente?.nombre,item.paciente?.identificacion,item.establecimiento_origen?.nombre,item.estado?.nombre].join(' ').toLowerCase().includes(term))})
const pendingCount=computed(()=>references.value.filter(item=>![5,6,7,8].includes(Number(item.estado?.id||item.estado_id))).length),completedCount=computed(()=>references.value.filter(item=>[5,6].includes(Number(item.estado?.id||item.estado_id))).length)
const formatDate=value=>value?new Intl.DateTimeFormat('es-CO',{dateStyle:'medium'}).format(new Date(value)):'Sin fecha'
async function load(){controller?.abort();controller=new AbortController();loading.value=true;error.value='';try{const fn=view.value==='pending'?listarReferenciasPendientes:listarReferencias;references.value=array(await fn({...filters},controller.signal))}catch(reason){if(reason.name!=='AbortError')error.value=obtenerMensajeError(reason)}finally{loading.value=false}}
function clear(){Object.keys(filters).forEach(key=>filters[key]='');localSearch.value='';view.value='all';load()}
onMounted(async()=>{const [catalogResult,statsResult]=await Promise.allSettled([consultarCatalogosReferencia(),consultarEstadisticasReferencias({})]);if(catalogResult.status==='fulfilled'){const source=catalogResult.value?.data||catalogResult.value;catalogs.estados=pick(source,['estados_referencia','estados']);catalogs.prioridades=pick(source,['prioridades_referencia','prioridades'])}if(statsResult.status==='fulfilled')stats.value=statsResult.value?.data||statsResult.value||{};await load()});onBeforeUnmount(()=>controller?.abort())
</script>

<style scoped>
.referral-hero{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.5rem;border-radius:1rem;background:linear-gradient(120deg,#084f81,#138fbd);color:#fff;box-shadow:0 14px 34px rgba(9,79,130,.2)}.referral-hero>div>span,.results-card .card-header small{font-size:.61rem;font-weight:800;letter-spacing:.08em}.referral-hero h1{margin:.2rem 0;font-size:1.65rem}.referral-hero p{margin:0;opacity:.82}.hero-actions{display:flex;gap:.6rem}.metric-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:.8rem}.metric-grid article{display:flex;align-items:center;gap:.7rem;padding:1rem;border:1px solid #e0e8ef;border-radius:.85rem;background:#fff;box-shadow:0 7px 20px rgba(25,63,95,.05)}.metric-grid article>span{display:grid;place-items:center;width:43px;height:43px;border-radius:12px;font-size:1.15rem}.metric-grid .blue{background:#e8f4fc;color:#247daf}.metric-grid .amber{background:#fff3df;color:#be761c}.metric-grid .green{background:#e8f8f0;color:#25865e}.metric-grid .purple{background:#eeebff;color:#6b5fc8}.metric-grid small,.metric-grid strong{display:block}.metric-grid small{color:#7e8c9b;font-size:.65rem}.metric-grid strong{font-size:1.35rem}.metric-grid em{font-size:.7rem;font-style:normal}.filters-card,.results-card{overflow:hidden;border:1px solid #dfe7ee;border-radius:1rem;box-shadow:0 9px 28px rgba(25,63,95,.06)}.results-card .card-header{display:flex;align-items:center;justify-content:space-between;padding:1rem 1.2rem;background:#fbfcfe}.local-search{display:flex;align-items:center;gap:.4rem;padding:.42rem .6rem;border:1px solid #dfe6ec;border-radius:.55rem;background:#fff}.local-search input{width:180px;border:0;outline:0;font-size:.7rem}.local-search span{padding:.15rem .4rem;border-radius:10px;background:#e8f3fb;color:var(--bs-primary);font-size:.62rem}.table th{padding:.75rem .85rem;background:#f7f9fb;color:#718096;font-size:.61rem;text-transform:uppercase}.table td{padding:.8rem .85rem}.reference-number,.cell-main,.cell-sub{display:block}.reference-number{color:var(--bs-primary);font-size:.75rem}.cell-main,.cell-text{font-size:.72rem}.cell-sub{color:#8491a0;font-size:.62rem}.priority,.status{display:inline-flex;align-items:center;gap:.3rem;padding:.28rem .5rem;border-radius:20px;background:color-mix(in srgb,var(--status) 13%,white);color:var(--status);font-size:.62rem;font-weight:700}.status i{font-size:.4rem}.empty{text-align:center;padding:4rem;color:#718096}.empty i{font-size:2.8rem;color:#a9bfce}.empty h3{margin:.7rem 0 .2rem;font-size:1rem}@media(max-width:991px){.metric-grid{grid-template-columns:repeat(2,1fr)}.referral-hero{align-items:flex-start;flex-direction:column}}@media(max-width:575px){.metric-grid{grid-template-columns:1fr}.hero-actions{width:100%;flex-direction:column}.results-card .card-header{align-items:flex-start;flex-direction:column;gap:.7rem}.local-search,.local-search input{width:100%}}
</style>
