<template>
    <b-row>
        <b-col lg="8">
            <b-card no-body>
                <b-card-header class="d-flex justify-content-between">
                    <div class="header-title">
                        <b-card-title>Activity Statistic</b-card-title>
                    </div>
                </b-card-header>
                <b-card-body class="pt-0">
                    <apexchart id="home-chart-05" :series="homechart5.series" type="bar" height="350"
                        :options="homechart5.options" />
                </b-card-body>
            </b-card>
        </b-col>
        <b-col lg="4">
            <b-card no-body>
                <div class="rounded d-flex align-items-center justify-content-center pb-4 pt-1">
                    <img src="/assets/images/page-img/39.png" class="img-fluid rounded" alt="banner-img">
                </div>
            </b-card>
        </b-col>
        <div class="col-md-6">
            <b-card no-body>
                <b-card-header class="d-flex justify-content-between">
                    <div class="header-title">
                        <b-card-title>Patient Distribution</b-card-title>
                    </div>
                </b-card-header>
                <b-card-body class="pt-0">
                    <div id="doc-chart-01" style="height: 415px;"></div>
                </b-card-body>
            </b-card>
        </div>
        <div class="col-md-6">
            <b-card no-body>
                <b-card-header class="d-flex justify-content-between">
                    <div class="header-title">
                        <b-card-title>Patients In</b-card-title>
                    </div>
                </b-card-header>
                <b-card-body class="pt-0">
                    <apexchart id="home-chart-05" :series="homechart6.series" type="bar" height="400"
                        :options="homechart6.options" />
                </b-card-body>
            </b-card>
        </div>
    </b-row>
    <b-row>
        <b-col lg="4">
            <b-card no-body>
                <b-card-header class="d-flex justify-content-between">
                    <div class="header-title">
                        <b-card-title>Patients Satisfactions</b-card-title>
                    </div>
                </b-card-header>
                <b-card-body>
                    <h2>3,897<span class="text-success font-size-14 ms-3 me-3"><i
                                class="ri-arrow-up-fill me-2"></i>+3.3%</span><small
                            class="text-secondary font-size-14">Generated by
                            clients</small>
                    </h2>

                    <div class="progress mt-3">
                        <div v-for="(bar, index) in progressBars" :key="index" class="progress-bar" :class="bar.color"
                            role="progressbar" :aria-valuenow="bar.value" aria-valuemin="0" aria-valuemax="100"
                            :style="{ width: bar.width + '%' }"></div>
                    </div>

                    <div class="table-responsive mt-4 mb-0">
                        <table class="table mb-0 table-borderless">
                            <tbody>
                                <tr v-for="(row, index) in tableData" :key="index">
                                    <td>
                                        <div :class="['profile-avatar', row.status, 'mt-4']"></div>
                                    </td>
                                    <td>
                                        <h4>{{ row.label }}</h4>
                                    </td>
                                    <td><span class="text-muted">{{ row.value }}</span></td>
                                    <td>{{ row.percentage }}%</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </b-card-body>
            </b-card>
        </b-col>
        <b-col lg="4">
            <b-card no-body>
                <b-card-header class="d-flex justify-content-between pb-0">
                    <div class="header-title">
                        <b-card-title>Tasks</b-card-title>
                    </div>
                    <div class="card-header-toolbar d-flex align-items-center">
                        <ul class="nav nav-pills custom-nav-pills flex-nowrap" id="myTab" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="home-tab" data-bs-toggle="tab" href="#home" role="tab"
                                    aria-selected="true">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab"
                                    aria-selected="false">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="contact-tab" data-bs-toggle="tab" href="#contact" role="tab"
                                    aria-selected="false">Contact</a>
                            </li>
                        </ul>
                    </div>
                </b-card-header>

                <b-card-body>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel">
                            <div v-for="task in taskshome" :key="task.id"
                                class="d-flex justify-content-between tasks-card">
                                <div class="custom-control custom-checkbox d-flex align-items-center gap-1">
                                    <input type="checkbox" class="custom-control-input" :id="'customCheck' + task.id"
                                        v-model="task.completed">{{ ' ' }}
                                    <label class="custom-control-label ms-1" :for="'customCheck' + task.id">{{
                                        task.text }}</label>
                                </div>
                                <div>
                                    <i class="ri-close-line" @click="removeTask(task.id)"></i>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="profile" role="tabpanel">
                            <div v-for="task in tasksprofile" :key="task.id"
                                class="d-flex justify-content-between tasks-card">
                                <div class="custom-control custom-checkbox d-flex align-items-center gap-1">
                                    <input type="checkbox" class="custom-control-input" :id="'customCheck' + task.id"
                                        v-model="task.completed">{{ '' }}
                                    <label class="custom-control-label ms-1" :for="'customCheck' + task.id">{{
                                        task.text }}</label>
                                </div>
                                <div>
                                    <i class="ri-close-line" @click="removeTask(task.id)"></i>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade show" id="contact" role="tabpanel">
                            <div v-for="task in taskscontact" :key="task.id"
                                class="d-flex justify-content-between tasks-card">
                                <div class="custom-control custom-checkbox d-flex align-items-center gap-1">
                                    <input type="checkbox" class="custom-control-input" :id="'customCheck' + task.id"
                                        v-model="task.completed">{{ '' }}
                                    <label class="custom-control-label ms-1" :for="'customCheck' + task.id">{{
                                        task.text }}</label>
                                </div>
                                <div>
                                    <i class="ri-close-line" @click="removeTask(task.id)"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </b-card-body>
            </b-card>
        </b-col>
        <b-col lg="4">
            <b-card no-body>
                <div class="p-4 d-flex justify-content-between border-bottom">
                    <div class="header-title">
                        <b-card-title>Patient Timeline</b-card-title>
                    </div>
                    <div class="card-header-toolbar d-flex align-items-center">
                        <div class="dropdown">
                            <span class="text-primary" id="dropdownMenuButton4" data-bs-toggle="dropdown">
                                View All
                            </span>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton4">
                                <a class="dropdown-item d-flex" href="#"><i class="ri-eye-fill me-2"></i>View</a>
                                <a class="dropdown-item d-flex" href="#"><i
                                        class="ri-delete-bin-6-fill me-2"></i>Delete</a>
                                <a class="dropdown-item d-flex" href="#"><i class="ri-pencil-fill me-2"></i>Edit</a>
                                <a class="dropdown-item d-flex" href="#"><i class="ri-printer-fill me-2"></i>Print</a>
                                <a class="dropdown-item d-flex" href="#"><i
                                        class="ri-file-download-fill me-2"></i>Download</a>
                            </div>
                        </div>
                    </div>
                </div>
                <b-card-body>
                    <ul class="timeline">
                        <li v-for="event in timelineEvents" :key="event.id">
                            <div class="timeline-dots mt-1" :class="event.dotClass"></div>
                            <h6 class="float-start mb-1 mt-2">{{ event.title }}</h6>
                            <small class="float-end mt-1 mt-2">{{ event.date }}</small>
                            <div class="d-inline-block w-100">
                                <p>{{ event.description }}</p>
                            </div>
                        </li>
                    </ul>
                </b-card-body>
            </b-card>
        </b-col>
    </b-row>
    <b-row>
        <b-col lg="8">
            <b-card no-body>
                <div class="p-4 d-flex justify-content-between border-bottom pb-0">
                    <div class="header-title">
                        <b-card-title>Patients Lists </b-card-title>
                    </div>
                    <div class="card-header-toolbar d-flex align-items-center">
                        <div class="dropdown">
                            <span class="ri-more-fill text-primary" id="dropdownMenuButton5" data-bs-toggle="dropdown">
                            </span>
                            <div class="dropdown-menu dropdown-menu-end iq-dropdown"
                                aria-labelledby="dropdownMenuButton5">
                                <a class="dropdown-item" href="#"><i class="ri-eye-fill me-2"></i>View</a>
                                <a class="dropdown-item" href="#"><i class="ri-delete-bin-6-fill me-2"></i>Delete</a>
                                <a class="dropdown-item" href="#"><i class="ri-pencil-fill me-2"></i>Edit</a>
                                <a class="dropdown-item" href="#"><i class="ri-printer-fill me-2"></i>Print</a>
                                <a class="dropdown-item" href="#"><i class="ri-file-download-fill me-2"></i>Download</a>
                            </div>
                        </div>
                    </div>
                </div>
                <b-card-body>
                    <div class="table-responsive mb-0">
                        <table class="table mb-0 table-borderless">
                            <thead>
                                <tr>
                                    <th scope="col">Patient</th>
                                    <th scope="col">E-mail Id</th>
                                    <th scope="col">Contact</th>
                                    <th scope="col">Disease</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="patient in patientsList" :key="patient.email">
                                    <td>{{ patient.name }}</td>
                                    <td>{{ patient.email }}</td>
                                    <td>{{ patient.contact }}</td>
                                    <td>{{ patient.disease }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </b-card-body>
            </b-card>
        </b-col>
        <b-col lg="4">
            <b-card no-body>
                <b-card-header class="d-flex justify-content-between">
                    <div class="header-title">
                        <b-card-title>Patients Reports</b-card-title>
                    </div>
                </b-card-header>
                <b-card-body>
                    <ul class="report-lists m-0 p-0">
                        <li v-for="report in reports" :key="report.name"
                            :class="`d-flex ${report.marginBottom === false ? '' : 'mb-4'} align-items-center justify-content-between`">
                            <div class="media-support-info">
                                <h6>{{ report.name }}</h6>
                                <a href="#">View report</a>
                            </div>
                            <button type="button" class="btn"
                                :class="report.onHold ? 'btn-danger-subtle' : 'btn-info-subtle'">
                                {{ report.onHold ? 'On Hold' : 'Download' }}
                            </button>
                        </li>
                    </ul>
                </b-card-body>
            </b-card>
        </b-col>
    </b-row>
</template>
<script setup>
import { ref, reactive, onBeforeUnmount, onMounted } from 'vue'
import * as am4core from "@amcharts/amcharts4/core";
import * as am4charts from "@amcharts/amcharts4/charts";
import am4themes_animated from "@amcharts/amcharts4/themes/animated";

const homechart5 = reactive({
    series: [{
        name: 'PRODUCT A',
        data: [44, 55, 41, 67, 22, 43]
    }, {
        name: 'PRODUCT B',
        data: [13, 23, 20, 8, 13, 27]
    }, {
        name: 'PRODUCT C',
        data: [11, 17, 15, 15, 21, 14]
    }],
    options: {
        chart: {
            type: 'bar',
            height: 350,
            stacked: true,
            toolbar: {
                show: true
            },
            zoom: {
                enabled: true
            }
        },
        colors: ['#089bab', '#FC9F5B', '#5bc5d1'],
        responsive: [{
            breakpoint: 480,
            options: {
                legend: {
                    position: 'bottom',
                    offsetX: -10,
                    offsetY: 0
                }
            }
        }],
        plotOptions: {
            bar: {
                horizontal: false,
            },
        },
        xaxis: {
            type: 'datetime',
            categories: ['01/01/2011 GMT', '01/02/2011 GMT', '01/03/2011 GMT', '01/04/2011 GMT',
                '01/05/2011 GMT', '01/06/2011 GMT'
            ],
        },
        legend: {
            position: 'right',
            offsetY: 40
        },
        fill: {
            opacity: 1
        }

    }
})

onMounted(() => {
    // Initialize amCharts
    am4core.useTheme(am4themes_animated);

    let chart = am4core.create("doc-chart-01", am4charts.RadarChart);

    chart.data = [
        { country: "USA", visits: 2025 },
        { country: "China", visits: 1882 },
        { country: "Japan", visits: 1809 },
        { country: "Germany", visits: 1322 },
        { country: "UK", visits: 1122 },
        { country: "France", visits: 1114 },
        { country: "India", visits: 984 },
        { country: "Spain", visits: 711 },
        { country: "Netherlands", visits: 665 },
        { country: "Russia", visits: 580 },
        { country: "South Korea", visits: 443 },
        { country: "Canada", visits: 441 }
    ];

    chart.rtl = true;
    chart.innerRadius = am4core.percent(40);

    let categoryAxis = chart.xAxes.push(new am4charts.CategoryAxis());
    categoryAxis.renderer.grid.template.location = 0;
    categoryAxis.dataFields.category = "country";
    categoryAxis.renderer.minGridDistance = 60;
    categoryAxis.renderer.inversed = true;
    categoryAxis.renderer.labels.template.location = 0.5;
    categoryAxis.renderer.grid.template.strokeOpacity = 0.08;

    chart.seriesContainer.zIndex = -10;

    let valueAxis = chart.yAxes.push(new am4charts.ValueAxis());
    valueAxis.min = 0;
    valueAxis.extraMax = 0.1;
    valueAxis.renderer.grid.template.strokeOpacity = 0.08;

    let series = chart.series.push(new am4charts.RadarColumnSeries());
    series.dataFields.categoryX = "country";
    series.dataFields.valueY = "visits";
    series.tooltipText = "{valueY.value}";
    series.columns.template.strokeOpacity = 0;
    series.columns.template.radarColumn.cornerRadius = 5;
    series.columns.template.radarColumn.innerCornerRadius = 0;

    chart.colors.list = [
        am4core.color("#279fac"),
        am4core.color("#ffb57e"),
        am4core.color("#279fac"),
        am4core.color("#ffb57e"),
        am4core.color("#279fac"),
        am4core.color("#ffb57e"),
        am4core.color("#279fac"),
        am4core.color("#ffb57e"),
        am4core.color("#279fac"),
        am4core.color("#ffb57e"),
        am4core.color("#279fac"),
        am4core.color("#ffb57e")
    ];

    chart.zoomOutButton.disabled = true;
    series.columns.template.adapter.add("fill", (fill, target) => {
        return chart.colors.getIndex(target.dataItem.index);
    });

    // Dynamically change the data
    setInterval(() => {
        chart.data.forEach(item => {
            item.visits *= Math.random() * 0.5 + 0.5;
            item.visits += 10;
        });
        chart.invalidateRawData();
    }, 2000);

    series.columns.template.adapter.add("fill", (fill, target) => {
        return chart.colors.getIndex(target.dataItem.index);
    });

    categoryAxis.sortBySeries = series;

    chart.cursor = new am4charts.RadarCursor();
    chart.cursor.behavior = "none";
    chart.cursor.lineX.disabled = true;
    chart.cursor.lineY.disabled = true;

    chart.logo.disabled = true;

    // Clean up chart when component unmounts
    onBeforeUnmount(() => {
        if (chart) {
            chart.dispose();
        }
    });
});

const homechart6 = reactive({
    series: [
        {
            name: "Male",
            data: [44, 90, 90, 60, 115],

        },
        {
            name: "Female",
            data: [35, 80, 100, 70, 95],
        },
    ],
    options: {
        chart: {
            type: 'bar',
            height: 400,
            toolbar: {
                show: false, // Disable the toolbar (including zoom and other options)
            },
        },
        plotOptions: {
            bar: {
                horizontal: !1,
                columnWidth: "30%",
                endingShape: "rounded",
            },
        },
        dataLabels: {
            enabled: !1,
        },
        stroke: {
            show: !0,
            width: 1,
        },
        colors: ["#089bab", "#FC9F5B"],
        xaxis: {
            min: 1,
            max: 5,
            tickAmount: 10,
        },
        tooltip: {
            y: {
                formatter: function (e) {
                    return "$ " + e + " thousands";
                },
            },
        },
    }
});

const progressBars = reactive([
    { color: 'bg-primary', width: 40, value: 40 },
    { color: 'bg-warning', width: 20, value: 20 },
    { color: 'bg-info', width: 10, value: 10 },
    { color: 'bg-danger', width: 40, value: 40 },
    { color: 'bg-success', width: 20, value: 20 },
    { color: 'bg-secondary', width: 10, value: 10 },
]);

const tableData = reactive([
    { status: 'status-online', label: 'Excellent', value: 2400, percentage: 60 },
    { status: 'status-blue', label: 'Very Good', value: 1200, percentage: 30 },
    { status: 'status-primary', label: 'Good', value: 240, percentage: 6 },
    { status: 'status-info', label: 'Fair', value: 80, percentage: 2 },
    { status: 'status-away', label: 'Poor', value: 40, percentage: 1 },
    { status: 'status-danger', label: 'Very Poor', value: 40, percentage: 1 },
]);


const taskshome = ref([
    { id: 1, text: 'You should check in some of below.', completed: false },
    { id: 2, text: 'Get the address of customer', completed: false },
    { id: 3, text: 'Contact Vendor for parcel', completed: false },
    { id: 4, text: 'Refuel delivery truck', completed: false },
    { id: 5, text: 'Pick up for order no. 334', completed: false },
    { id: 6, text: 'Pay taxes for every bill', completed: false },
    { id: 7, text: 'I am designers & I have no life', completed: false },
    { id: 8, text: 'This is a good product. Buy it', completed: false },
]);

const tasksprofile = ref([
    { id: 1, text: 'You should check in on some of below.', completed: false },
    { id: 2, text: 'You should check in on some of below.', completed: false },
]);

const taskscontact = ref([
    { id: 1, text: 'You should check in on some of below.', completed: false },
    { id: 2, text: 'You should check in on some of below.', completed: false },
    { id: 3, text: 'You should check in on some of below.', completed: false },
]);

const removeTask = (id) => {
    tasks.value = tasks.value.filter(task => task.id !== id);
};

const timelineEvents = ref([
    {
        id: 1,
        title: 'Patient Checkup',
        date: '23 November 2019',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque',
        dotClass: '',
    },
    {
        id: 2,
        title: 'Patient Admit',
        date: '24 November 2019',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque',
        dotClass: 'border-success',
    },
    {
        id: 3,
        title: 'Treatment Starts',
        date: '24 November 2019',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque',
        dotClass: 'border-primary',
    },
    {
        id: 4,
        title: 'Patient Discharge',
        date: '30 November 2019',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque',
        dotClass: 'border-warning',
    },
]);

const patientsList = ref([
    {
        name: 'Petey Cruiser',
        email: 'peteycruiser01@gmail.com',
        contact: '+1-202-555-0146',
        disease: 'Fever',
    },
    {
        name: 'Anna Sthesia',
        email: 'annasthesia121@gmail.com',
        contact: '+1-202-555-0164',
        disease: 'Cancer',
    },
    {
        name: 'Paul Molive',
        email: 'paulmolive30@gmail.com',
        contact: '+1-202-555-0153',
        disease: 'Diabetes',
    },
    {
        name: 'Anna Mull',
        email: 'annamull07@gmail.com',
        contact: '+1-202-555-0154',
        disease: 'Eye',
    },
    {
        name: 'John Deo',
        email: 'johndeo123@gmail.com',
        contact: '+1-202-555-0155',
        disease: 'Lung',
    },
]);

const reports = ref([
    {
        name: 'X-ray.pdf',
        onHold: false,
    },
    {
        name: 'pathologyreport.pdf',
        onHold: false,
    },
    {
        name: 'laboratoryreports.pdf',
        onHold: true,
    },
    {
        name: 'operativereport.pdf',
        onHold: false,
        marginBottom: false
    },
]);
</script>