<template>
  <main class="hh-page appointment-detail">
    <router-link to="/consulta-externa/agenda" class="hh-back-link"><i class="ph ph-arrow-left"></i> Volver a la agenda</router-link>
    <div v-if="loading" class="text-center py-5"><span class="spinner-border text-primary"></span></div>
    <div v-else-if="error&&!appointment" class="alert alert-danger mt-3">{{error}}</div>
    <template v-else-if="appointment">
      <section class="detail-hero"><span>{{initials(appointment.paciente)}}</span><div><small>CITA #{{appointment.id}}</small><h1>{{appointment.paciente}}</h1><p>{{appointment.identificacion}} · {{appointment.especialidad||appointment.servicio}}</p></div><em>{{statusName}}</em></section>
      <div v-if="error" class="alert alert-danger mt-3">{{error}}</div><div v-if="notice" class="alert alert-success mt-3">{{notice}}</div>
      <section class="detail-data"><article><small>Fecha y hora</small><strong>{{formatDate(appointment.fecha_inicio)}}</strong></article><article><small>Consultorio</small><strong>{{appointment.consultorio}}</strong></article><article><small>Profesional</small><strong>{{appointment.profesional}}</strong></article><article><small>Contacto</small><strong>{{appointment.celular||appointment.telefono||'No informado'}}</strong></article><article><small>Orden de trabajo</small><strong>#{{appointment.id_orden_trabajo||'—'}}</strong></article><article><small>Orden de servicio</small><strong>#{{appointment.id_orden_de_servicio||'—'}}</strong></article></section>
      <section class="actions"><div><small>ACCIONES ADMINISTRATIVAS</small><h2>Control de la cita</h2></div><div><button class="btn btn-outline-primary" @click="open('reschedule')"><i class="ph ph-calendar-dots me-1"></i>Reprogramar</button><button class="btn btn-outline-primary" @click="open('document')"><i class="ph ph-file-pdf me-1"></i>Adjuntar PDF</button><button class="btn btn-primary" @click="open('close')"><i class="ph ph-check-circle me-1"></i>Cierre administrativo</button></div></section>
      <div class="content-grid"><section><header><h2>Información asistencial</h2></header><div class="info-list"><div><small>Servicio</small><strong>{{appointment.servicio||'No informado'}}</strong></div><div><small>Personal de apoyo</small><strong>{{appointment.profesional_apoyo||'No asignado'}}</strong></div><div><small>Hora de llegada</small><strong>{{appointment.hora_llegada||'No registrada'}}</strong></div><div><small>Número de llamados</small><strong>{{appointment.llamadas||0}}</strong></div></div></section><section><header><h2>Trazabilidad</h2><span>{{history.length}}</span></header><div v-if="!history.length" class="empty">Sin eventos registrados.</div><div v-else class="timeline"><article v-for="(item,index) in history" :key="item.id||index"><span></span><div><small>{{formatDate(item.fecha||item.created_at)}}</small><strong>{{item.usuario_nota||item.usuario||'Sistema'}}</strong><p>{{item.observacion||item.nota||item.descripcion}}</p></div></article></div></section></div>
    </template>
    <Teleport to="body"><div v-if="action" class="detail-layer" @mousedown.self="closeModal"><section class="detail-modal"><header><div><small>GESTIÓN DE CITA</small><h3>{{titles[action]}}</h3></div><button class="btn-close" @click="closeModal"></button></header><form @submit.prevent="execute"><div class="modal-body"><div v-if="modalError" class="alert alert-danger">{{modalError}}</div><template v-if="action==='reschedule'"><p class="old-date">Fecha actual: <strong>{{formatDate(appointment.fecha_inicio)}}</strong></p><label class="form-label">Nueva fecha y hora *</label><input v-model="form.date" type="datetime-local" class="form-control" required><label class="form-label mt-3">Consultorio *</label><select v-model="form.officeId" class="form-select" required><option v-for="item in offices" :key="id(item)" :value="id(item)">{{name(item)}}</option></select><label class="form-label mt-3">Profesional *</label><input v-model.number="form.professionalId" type="number" min="1" class="form-control" required></template><template v-if="action==='document'"><label class="form-label">Documento PDF *</label><input type="file" accept="application/pdf,.pdf" class="form-control" required @change="selectFile"><small>Máximo 6048 KB. Una nueva carga puede reemplazar el documento anterior.</small></template><template v-if="action==='close'"><div class="warning"><i class="ph ph-warning"></i>La cita cambiará a cierre administrativo y la acción quedará en la trazabilidad.</div></template></div><footer><button type="button" class="btn btn-outline-secondary" @click="closeModal">Cancelar</button><button class="btn btn-primary" :disabled="saving"><span v-if="saving" class="spinner-border spinner-border-sm me-2"></span>Confirmar</button></footer></form></section></div></Teleport>
  </main>
</template>
<script setup>
import{computed,onMounted,reactive,ref}from'vue';import{useRoute}from'vue-router';import{obtenerMensajeError}from'@/services/api';import{adjuntarDocumentoCita,cerrarAdministrativamente,consultarCita,consultarTrazabilidadCita,listarConsultorios,reagendarCita}from'@/services/intramural';
const route=useRoute(),appointment=ref(null),history=ref([]),offices=ref([]),loading=ref(true),saving=ref(false),error=ref(''),notice=ref(''),modalError=ref(''),action=ref(''),pdf=ref(''),form=reactive({date:'',officeId:'',professionalId:''}),titles={reschedule:'Reprogramar cita',document:'Adjuntar documento clínico',close:'Cierre administrativo'},array=v=>Array.isArray(v)?v:Array.isArray(v?.data)?v.data:[],id=i=>i?.id??i?.id_consultorio,name=i=>i?.nombre??i?.name??i?.consultorio??`#${id(i)}`,initials=v=>String(v||'P').split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase(),formatDate=v=>v?new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'}).format(new Date(String(v).replace(' ','T'))):'No informado',statusName=computed(()=>appointment.value?.estado_cita||appointment.value?.estado||({1:'Activa',2:'Atendida',3:'Solicitada',4:'Anulada',5:'Bloqueada',6:'No asistió',7:'Cierre administrativo'}[Number(appointment.value?.status)]||'Programada'));
async function load(){loading.value=true;error.value='';try{const[d,h,o]=await Promise.all([consultarCita(route.params.id),consultarTrazabilidadCita(route.params.id),listarConsultorios()]);appointment.value=d?.data||d;history.value=array(h);offices.value=array(o)}catch(e){error.value=obtenerMensajeError(e)}finally{loading.value=false}}function open(type){action.value=type;modalError.value='';pdf.value='';if(type==='reschedule')Object.assign(form,{date:String(appointment.value.fecha_inicio).replace(' ','T').slice(0,16),officeId:appointment.value.id_consultorio,professionalId:appointment.value.id_profesional})}function closeModal(){if(!saving.value)action.value=''}function selectFile(event){const file=event.target.files?.[0];if(!file)return;if(file.type!=='application/pdf'||file.size>6048*1024){modalError.value='Seleccione un PDF de máximo 6048 KB.';return}const reader=new FileReader();reader.onload=()=>pdf.value=reader.result;reader.readAsDataURL(file)}async function execute(){saving.value=true;modalError.value='';try{if(action.value==='reschedule')await reagendarCita(appointment.value.id,{id_profesional:Number(form.professionalId),fecha_inicio:`${form.date.replace('T',' ')}:00`,id_consultorio:Number(form.officeId),id_actividad:Number(appointment.value.id_actividad)});if(action.value==='document'){if(!pdf.value)throw new Error('Seleccione un archivo PDF válido.');await adjuntarDocumentoCita(appointment.value.id,pdf.value)}if(action.value==='close')await cerrarAdministrativamente(appointment.value.id);action.value='';notice.value='Acción realizada correctamente.';await load()}catch(e){modalError.value=obtenerMensajeError(e)}finally{saving.value=false}}onMounted(load)
</script>
<style scoped>.detail-hero{display:flex;align-items:center;gap:.8rem;margin-top:1rem;padding:1.3rem 1.5rem;border-radius:1rem;background:linear-gradient(120deg,#124c76,#148bac);color:#fff}.detail-hero>span{display:grid;place-items:center;width:50px;height:50px;border-radius:14px;background:#ffffff24;font-weight:800}.detail-hero>div{flex:1}.detail-hero small,.detail-hero h1,.detail-hero p{display:block;margin:0}.detail-hero h1{font-size:1.25rem}.detail-hero p{opacity:.8}.detail-hero em{padding:.4rem .7rem;border-radius:20px;background:#ffffff24;font-style:normal}.detail-data{display:grid;grid-template-columns:repeat(3,1fr);gap:.7rem;margin-top:1rem}.detail-data article,.content-grid>section,.actions{padding:.85rem;border:1px solid #dfe7ed;border-radius:.75rem;background:#fff}.detail-data small,.detail-data strong{display:block}.detail-data small,.actions small{color:#7b8997;font-size:.67rem}.actions{display:flex;align-items:center;justify-content:space-between;margin-top:1rem}.actions h2{font-size:1rem}.actions>div:last-child{display:flex;gap:.5rem}.content-grid{display:grid;grid-template-columns:1fr 1.3fr;gap:.8rem;margin-top:1rem}.content-grid section>header{display:flex;justify-content:space-between;padding-bottom:.6rem;border-bottom:1px solid #e5eaee}.content-grid h2{font-size:.95rem}.info-list div{padding:.65rem;border-bottom:1px solid #edf0f2}.info-list small,.info-list strong{display:block}.timeline{display:grid;gap:.5rem;padding-top:.7rem}.timeline article{display:grid;grid-template-columns:10px 1fr;gap:.6rem}.timeline article>span{width:9px;height:9px;margin-top:.35rem;border-radius:50%;background:#2780aa}.timeline small,.timeline strong{display:block}.timeline p{margin:.15rem 0;color:#718292;font-size:.71rem}.empty{text-align:center;padding:2rem;color:#788897}.detail-layer{position:fixed;inset:0;z-index:2100;display:grid;place-items:center;background:#071522bd}.detail-modal{width:min(540px,calc(100% - 2rem));border-radius:1rem;background:#fff}.detail-modal>header{display:flex;justify-content:space-between;padding:1rem 1.2rem;border-bottom:1px solid #e3e9ed}.detail-modal header small{font-size:.68rem;font-weight:800}.detail-modal h3{font-size:1rem}.detail-modal .modal-body{padding:1.2rem}.detail-modal footer{display:flex;justify-content:flex-end;gap:.5rem;padding:1rem 1.2rem;border-top:1px solid #e3e9ed}.old-date,.warning{padding:.7rem;border-radius:.65rem;background:#eef7fc}.warning{display:flex;gap:.5rem;background:#fff3df;color:#96601e}@media(max-width:800px){.detail-data{grid-template-columns:repeat(2,1fr)}.content-grid{grid-template-columns:1fr}.actions{align-items:flex-start;flex-direction:column;gap:.7rem}}@media(max-width:550px){.detail-data{grid-template-columns:1fr}.actions>div:last-child{flex-direction:column;width:100%}}</style>
