<template>
  <main class="hh-page professional-hours">
    <router-link to="/parametrizacion/general?seccion=offices" class="hh-back-link"><i class="ph ph-arrow-left"></i> Parametrización general</router-link>
    <section class="hours-hero">
      <div><span>PARAMETRIZACIÓN INTRAMURAL</span><h1>Disponibilidad de profesionales</h1><p>Configure el horario semanal recurrente utilizado por la agenda.</p></div>
      <div class="hero-actions"><button class="btn btn-outline-light" :disabled="!professionalId" @click="openBlock"><i class="ph ph-calendar-x me-1"></i>Excepción de agenda</button><button class="btn btn-light text-primary" :disabled="!professionalId" @click="openCreate"><i class="ph ph-plus me-1"></i>Nueva franja</button></div>
    </section>

    <section class="selectors">
      <div><label class="form-label">Especialidad</label><SearchSelect v-model="specialtyId" :options="specialties" :value-getter="id" :label-getter="name" placeholder="Seleccione una especialidad" @change="loadProfessionals"/></div>
      <div><label class="form-label">Profesional</label><SearchSelect v-model="professionalId" :options="professionals" :value-getter="id" :label-getter="name" placeholder="Seleccione un profesional" :disabled="!specialtyId||loadingProfessionals" @change="loadHours"/></div>
    </section>
    <div v-if="notice.text" class="alert mt-3" :class="`alert-${notice.type}`">{{ notice.text }}</div>

    <section class="hours-card mt-3">
      <header><div><small>PROGRAMACIÓN SEMANAL RECURRENTE</small><h2>{{ professionalName }}</h2></div><span>{{ hours.length }} franjas</span></header>
      <div v-if="loading" class="state"><span class="spinner-border text-primary"></span><p>Consultando disponibilidad…</p></div>
      <div v-else-if="!professionalId" class="state"><i class="ph ph-user-focus"></i><p>Seleccione un profesional para consultar sus horarios.</p></div>
      <div v-else class="week-grid">
        <article v-for="day in week" :key="day.id" class="day-card">
          <header><span>{{ day.short }}</span><div><strong>{{ day.name }}</strong><small>{{ day.blocks.length }} {{ day.blocks.length===1?'franja':'franjas' }}</small></div><button class="btn btn-sm btn-light" title="Agregar franja" @click="openCreate(day.id)"><i class="ph ph-plus"></i></button></header>
          <div v-if="!day.blocks.length" class="day-empty">Sin disponibilidad</div>
          <div v-else class="day-blocks"><div v-for="item in day.blocks" :key="item.id" class="time-block"><i class="ph ph-clock"></i><strong>{{ time(item.hora_inicio) }}–{{ time(item.hora_fin) }}</strong><div><button class="icon-btn edit" title="Editar" @click="openEdit(item)"><i class="ph ph-pencil-simple"></i></button><button class="icon-btn remove" title="Eliminar" :disabled="deletingId===item.id" @click="remove(item)"><span v-if="deletingId===item.id" class="spinner-border spinner-border-sm"></span><i v-else class="ph ph-trash"></i></button></div></div></div>
        </article>
      </div>
    </section>

    <Teleport to="body"><div v-if="modal" class="hours-layer" @mousedown.self="close"><section class="hours-modal" role="dialog" aria-modal="true"><header><div><small>HORARIO SEMANAL</small><h3>{{ editingId ? 'Editar franja' : 'Agregar franja' }}</h3></div><button class="btn-close" :disabled="saving" @click="close"></button></header><form @submit.prevent="save"><div class="modal-body"><div v-if="modalError" class="alert alert-danger">{{ modalError }}</div><label class="form-label">Día *</label><select v-model.number="form.day" class="form-select" required><option v-for="(day,index) in days" :key="day" :value="index+1">{{ day }}</option></select><div class="row g-3 mt-0"><div class="col-6"><label class="form-label">Hora inicial *</label><input v-model="form.start" type="time" class="form-control" required></div><div class="col-6"><label class="form-label">Hora final *</label><input v-model="form.end" type="time" class="form-control" required></div></div><div class="form-note mt-3"><i class="ph ph-info"></i><span>Los bloques contiguos son válidos. El sistema rechazará franjas superpuestas o que dejen citas activas por fuera.</span></div></div><footer><button type="button" class="btn btn-outline-secondary" :disabled="saving" @click="close">Cancelar</button><button class="btn btn-primary" :disabled="saving"><span v-if="saving" class="spinner-border spinner-border-sm me-2"></span>{{ saving ? 'Guardando...' : 'Guardar franja' }}</button></footer></form></section></div></Teleport>

    <Teleport to="body"><div v-if="blockModal" class="hours-layer" @mousedown.self="closeBlock"><section class="hours-modal"><header><div><small>EXCEPCIÓN DE AGENDA</small><h3>Bloquear una fecha específica</h3></div><button class="btn-close" :disabled="saving" @click="closeBlock"></button></header><form @submit.prevent="saveBlock"><div class="modal-body"><div v-if="blockError" class="alert alert-danger">{{ blockError }}</div><div class="form-note mb-3"><i class="ph ph-info"></i><span>Use esta opción para vacaciones, permisos o incapacidades. El horario semanal no será eliminado.</span></div><div class="row g-3"><div class="col-6"><label class="form-label">Desde *</label><input v-model="block.start" type="datetime-local" class="form-control" required></div><div class="col-6"><label class="form-label">Hasta *</label><input v-model="block.end" type="datetime-local" class="form-control" required></div></div><label class="form-label mt-3">Motivo *</label><textarea v-model.trim="block.note" class="form-control" rows="3" maxlength="255" required></textarea></div><footer><button type="button" class="btn btn-outline-secondary" :disabled="saving" @click="closeBlock">Cancelar</button><button class="btn btn-primary" :disabled="saving"><span v-if="saving" class="spinner-border spinner-border-sm me-2"></span>{{ saving?'Guardando...':'Bloquear espacio' }}</button></footer></form></section></div></Teleport>
  </main>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import SearchSelect from '@/components/form/SearchSelect.vue'
import { obtenerMensajeError } from '@/services/api'
import { actualizarHorarioProfesional, bloquearEspacioProfesional, consultarHorariosProfesional, eliminarHorarioProfesional, guardarHorariosProfesional, listarEspecialidades, listarProfesionalesEspecialidad } from '@/services/intramural'

const specialties=ref([]),professionals=ref([]),hours=ref([]),specialtyId=ref(''),professionalId=ref(''),loading=ref(false),loadingProfessionals=ref(false),saving=ref(false),deletingId=ref(null),modalError=ref(''),modal=ref(false),editingId=ref(null),blockModal=ref(false),blockError=ref('')
const notice=reactive({text:'',type:'success'}),days=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'],form=reactive({day:1,start:'08:00',end:'17:00'}),block=reactive({start:'',end:'',note:''})
const array=value=>Array.isArray(value)?value:Array.isArray(value?.data)?value.data:[],id=item=>item?.id??item?.id_especialidad??item?.id_user??item?.id_profesional,name=item=>item?.nombre??item?.name??item?.profesional??item?.especialidad??`#${id(item)}`,time=value=>String(value||'').slice(0,5)
const sortedHours=computed(()=>[...hours.value].sort((a,b)=>Number(a.id_dia)-Number(b.id_dia)||time(a.hora_inicio).localeCompare(time(b.hora_inicio))))
const week=computed(()=>days.map((day,index)=>({id:index+1,name:day,short:day.slice(0,2).toUpperCase(),blocks:sortedHours.value.filter(item=>Number(item.id_dia)===index+1)})))
const professionalName=computed(()=>professionalId.value?name(professionals.value.find(item=>String(id(item))===String(professionalId.value))):'Profesional no seleccionado')

async function loadProfessionals(){professionalId.value='';hours.value=[];notice.text='';if(!specialtyId.value){professionals.value=[];return}loadingProfessionals.value=true;try{professionals.value=array(await listarProfesionalesEspecialidad(specialtyId.value))}catch(error){showError(error)}finally{loadingProfessionals.value=false}}
async function loadHours(){hours.value=[];notice.text='';if(!professionalId.value)return;loading.value=true;try{hours.value=array(await consultarHorariosProfesional(professionalId.value))}catch(error){showError(error)}finally{loading.value=false}}
function openCreate(day=1){editingId.value=null;Object.assign(form,{day,start:'08:00',end:'17:00'});modalError.value='';modal.value=true}
function openEdit(item){editingId.value=item.id;Object.assign(form,{day:Number(item.id_dia),start:time(item.hora_inicio),end:time(item.hora_fin)});modalError.value='';modal.value=true}
function close(){if(!saving.value)modal.value=false}
const payload=()=>{const[sh,sm]=form.start.split(':').map(Number),[eh,em]=form.end.split(':').map(Number);return{dia:Number(form.day),hora_inicio:sh,minuto_inicio:sm,hora_fin:eh,minuto_fin:em}}
async function save(){if(form.end<=form.start){modalError.value='La hora final debe ser posterior a la hora inicial.';return}saving.value=true;modalError.value='';try{const data=payload();if(editingId.value)await actualizarHorarioProfesional(professionalId.value,editingId.value,data);else await guardarHorariosProfesional(professionalId.value,[data]);modal.value=false;await loadHours();showSuccess(editingId.value?'Horario actualizado correctamente.':'Horario creado correctamente.')}catch(error){modalError.value=obtenerMensajeError(error)}finally{saving.value=false}}
async function remove(item){if(!window.confirm(`¿Eliminar la franja ${time(item.hora_inicio)}–${time(item.hora_fin)} del ${item.dia||days[Number(item.id_dia)-1]}?`))return;deletingId.value=item.id;notice.text='';try{await eliminarHorarioProfesional(professionalId.value,item.id);await loadHours();showSuccess('Horario eliminado correctamente.')}catch(error){showError(error)}finally{deletingId.value=null}}
function openBlock(){const start=new Date(Date.now()+3600000);start.setMinutes(0,0,0);const end=new Date(start.getTime()+3600000),local=value=>new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,16);Object.assign(block,{start:local(start),end:local(end),note:''});blockError.value='';blockModal.value=true}
function closeBlock(){if(!saving.value)blockModal.value=false}
async function saveBlock(){if(block.end<=block.start){blockError.value='La fecha final debe ser posterior a la inicial.';return}saving.value=true;blockError.value='';try{await bloquearEspacioProfesional({id_user:Number(professionalId.value),id_profesional:Number(professionalId.value),fecha_inicio:`${block.start.replace('T',' ')}:00`,fecha_fin:`${block.end.replace('T',' ')}:00`,observacion:block.note});blockModal.value=false;showSuccess('Excepción de agenda registrada correctamente.')}catch(error){blockError.value=obtenerMensajeError(error)}finally{saving.value=false}}
function showError(error){notice.type='danger';notice.text=obtenerMensajeError(error)}function showSuccess(message){notice.type='success';notice.text=message}
onMounted(async()=>{try{specialties.value=array(await listarEspecialidades())}catch(error){showError(error)}})
</script>

<style scoped>
.hours-hero{display:flex;align-items:center;justify-content:space-between;margin-top:1rem;padding:1.4rem 1.5rem;border-radius:1rem;background:linear-gradient(120deg,#124c76,#148bac);color:#fff}.hours-hero span,.hours-card>header small,.hours-modal header small{font-size:.7rem;font-weight:800;letter-spacing:.08em}.hours-hero h1{margin:.2rem 0;font-size:1.55rem}.hours-hero p{margin:0;opacity:.82}.hero-actions{display:flex;gap:.5rem}.selectors{display:grid;grid-template-columns:repeat(2,1fr);gap:.7rem;margin-top:1rem;padding:.9rem;border:1px solid #dfe7ed;border-radius:.8rem;background:#fff}.hours-card{overflow:hidden;border:1px solid #dfe7ed;border-radius:.9rem;background:#fff}.hours-card>header{display:flex;justify-content:space-between;padding:1rem;border-bottom:1px solid #e5eaee}.hours-card h2{margin:.1rem 0;font-size:1rem}.hours-card>header>span{padding:.3rem .55rem;border-radius:20px;background:#e8f4fb;color:#287da7}.state{display:grid;place-items:center;padding:3rem;color:#778795}.state>i{font-size:2.4rem}.week-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem;padding:1rem;background:#f8fafc}.day-card{overflow:hidden;border:1px solid #dfe7ed;border-radius:.8rem;background:#fff}.day-card>header{display:flex;align-items:center;gap:.65rem;padding:.7rem;border-bottom:1px solid #edf1f4}.day-card>header>span{display:grid;place-items:center;width:38px;height:38px;border-radius:10px;background:#e9f5fb;color:#1879a5;font-weight:800}.day-card>header>div{flex:1}.day-card strong,.day-card small{display:block}.day-card small{color:#7a8999}.day-empty{padding:1.2rem;color:#98a4b1;text-align:center}.day-blocks{display:grid;gap:.45rem;padding:.65rem}.time-block{display:flex;align-items:center;gap:.5rem;padding:.6rem;border-radius:.6rem;background:#f5f8fb}.time-block>i{color:#2183ad}.time-block>strong{flex:1}.time-block>div{display:flex;gap:.25rem}.icon-btn{display:grid;place-items:center;width:30px;height:30px;border:0;border-radius:8px}.icon-btn.edit{background:#e8f3fc;color:#267aaa}.icon-btn.remove{background:#fff0f1;color:#bd4450}.hours-layer{position:fixed;inset:0;z-index:2100;display:grid;place-items:center;padding:1rem;background:#071522bd;backdrop-filter:blur(4px)}.hours-modal{width:min(540px,100%);overflow:hidden;border-radius:1rem;background:#fff;box-shadow:0 24px 70px #0005}.hours-modal>header{display:flex;justify-content:space-between;padding:1rem 1.2rem;border-bottom:1px solid #e3e9ed}.hours-modal h3{font-size:1.05rem}.hours-modal .modal-body{padding:1.2rem}.hours-modal footer{display:flex;justify-content:flex-end;gap:.5rem;padding:1rem 1.2rem;border-top:1px solid #e3e9ed}.form-note{display:flex;gap:.6rem;padding:.75rem;border-radius:.65rem;background:#eef7fc;color:#39708d;font-size:.82rem}.form-note i{font-size:1.15rem;flex:none}@media(max-width:700px){.hours-hero{align-items:flex-start;flex-direction:column;gap:1rem}.hero-actions{width:100%;flex-direction:column}.selectors,.week-grid{grid-template-columns:1fr}}
</style>
